namespace NextNet.Build.Production.Security;

/// <summary>
/// Options for configuring security headers middleware.
/// </summary>
public sealed class SecurityHeadersOptions
{
    /// <summary>
    /// Whether to enable security headers.
    /// </summary>
    public bool EnableSecurityHeaders { get; set; } = true;

    /// <summary>
    /// Whether to enable HSTS (HTTP Strict Transport Security).
    /// </summary>
    public bool EnableHsts { get; set; } = true;

    /// <summary>
    /// HSTS max-age in days.
    /// </summary>
    public int HstsMaxAgeDays { get; set; } = 365;

    /// <summary>
    /// Whether to include subdomains in HSTS.
    /// </summary>
    public bool HstsIncludeSubDomains { get; set; } = true;

    /// <summary>
    /// Whether to preload HSTS.
    /// </summary>
    public bool HstsPreload { get; set; } = false;

    /// <summary>
    /// X-Frame-Options header value.
    /// </summary>
    public string XFrameOptions { get; set; } = "DENY";

    /// <summary>
    /// X-Content-Type-Options header value.
    /// </summary>
    public string XContentTypeOptions { get; set; } = "nosniff";

    /// <summary>
    /// X-XSS-Protection header value.
    /// </summary>
    public string XssProtection { get; set; } = "1; mode=block";

    /// <summary>
    /// Referrer-Policy header value.
    /// </summary>
    public string ReferrerPolicy { get; set; } = "strict-origin-when-cross-origin";

    /// <summary>
    /// Permissions-Policy header value.
    /// </summary>
    public string PermissionsPolicy { get; set; } = "camera=(), microphone=(), geolocation=()";

    /// <summary>
    /// Content-Security-Policy header value.
    /// Generated by <see cref="ContentSecurityPolicyBuilder"/> if set, otherwise used directly.
    /// </summary>
    public string? ContentSecurityPolicy { get; set; }

    /// <summary>
    /// Paths that should not receive security headers.
    /// </summary>
    public HashSet<string> ExcludedPaths { get; set; } = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Custom headers to add alongside the defaults.
    /// </summary>
    public Dictionary<string, string> CustomHeaders { get; set; } = new();
}
