using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using NextNet.SourceGenerators.Emitters;
using NextNet.SourceGenerators.Models;
using NextNet.SourceGenerators.Utils;

namespace NextNet.SourceGenerators;
    /// <summary>
    /// NextNet route source generator. Reads the <c>nextnet.routes.json</c> manifest from
    /// <c>AdditionalFiles</c> and generates endpoint registration, DI registration,
    /// and wrapper classes for all discovered page, layout, API, and error routes.
    /// 
    /// Pipeline:
    ///   1. <c>RegisterPostInitializationOutput</c> emits marker attributes.
    ///   2. <c>AdditionalTextsProvider</c> reads routes.json → <c>RouteManifestModel</c>.
    ///   3. <c>SyntaxProvider</c> finds component classes with marker attributes.
    ///   4. Combined pipeline → <c>RegisterSourceOutput</c> generates code.
    /// </summary>
    /// <example>
    /// The generator is activated automatically when the <c>NextNetRouteGenerator</c> assembly
    /// is referenced as an analyzer. No manual instantiation is required.
    /// <code>
    /// // In your .csproj:
    /// &lt;ProjectReference Include="..\NextNet.SourceGenerators\NextNet.SourceGenerators.csproj"
    ///                   OutputItemType="Analyzer" ReferenceOutputAssembly="false" /&gt;
    /// </code>
    /// </example>
    [Generator]
    public sealed class NextNetRouteGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Embedded marker attribute source code emitted via RegisterPostInitializationOutput.
        /// These attributes are used by ForAttributeWithMetadataName for component discovery.
        /// </summary>
        internal const string MarkerAttributeSource = @"// <auto-generated />
#nullable enable
namespace NextNet
{
    /// <summary>
    /// Marks a class as a page component discoverable by the NextNet source generator.
    /// Applied automatically by the build convention; manual use is optional.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class PageComponentAttribute : System.Attribute
    {
        public string? Route { get; set; }
    }

    /// <summary>
    /// Marks a class as a layout component discoverable by the NextNet source generator.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class LayoutComponentAttribute : System.Attribute
    {
        public string? RoutePattern { get; set; }
    }

    /// <summary>
    /// Marks a class as an API route handler discoverable by the NextNet source generator.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class ApiRouteAttribute : System.Attribute
    {
        public string? RoutePattern { get; set; }
    }
}";

        /// <summary>
        /// The default app directory relative path used by NextNet conventions.
        /// </summary>
        internal const string DefaultAppDir = "app";

        /// <summary>
        /// The namespace for generated code types.
        /// </summary>
        internal const string GeneratedNamespace = "NextNet.Generated";

        /// <summary>
        /// Marker attribute fully qualified names for SyntaxProvider filtering.
        /// </summary>
        internal const string PageComponentAttributeName = "NextNet.PageComponentAttribute";
        internal const string LayoutComponentAttributeName = "NextNet.LayoutComponentAttribute";
        internal const string ApiRouteAttributeName = "NextNet.ApiRouteAttribute";

        /// <summary>
        /// Initializes the incremental generator pipeline.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Step 1: Register marker attributes
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("NextNet.Attributes.g.cs",
                    SourceText.From(MarkerAttributeSource, Encoding.UTF8));
            });

            // Step 2: Pipeline for route manifest (routes.json from AdditionalFiles)
            var manifestPipeline = context.AdditionalTextsProvider
                .Where(static file => IsRoutesJsonFile(file.Path))
                .Select(static (text, ct) =>
                {
                    try
                    {
                        var jsonText = text.GetText(ct);
                        var json = jsonText?.ToString();
                        if (string.IsNullOrEmpty(json))
                            return new RouteManifestModel();

                        var options = new JsonSerializerOptions
                        {
                            PropertyNameCaseInsensitive = true
                        };

                        var manifest = JsonSerializer.Deserialize<RouteManifestModel>(json!, options);
                        return manifest ?? new RouteManifestModel();
                    }
                    catch (Exception ex)
                    {
                        // JSON parse failure — return empty manifest.
                        // The outer RegisterSourceOutput will report ManifestEmpty (SKG002).
                        System.Diagnostics.Debug.WriteLine(
                            "[NextNet] Failed to parse routes.json: " + ex.Message);
                        return new RouteManifestModel();
                    }
                })
                .WithComparer(RouteManifestModelComparer.Instance);

            // Step 3: Pipeline for component classes (SyntaxProvider with marker attributes)
            var pageComponentPipeline = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    PageComponentAttributeName,
                    static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                    static (ctx, _) => ExtractComponentMetadata(ctx, "Page"))
                .Collect();

            var layoutComponentPipeline = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    LayoutComponentAttributeName,
                    static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                    static (ctx, _) => ExtractComponentMetadata(ctx, "Layout"))
                .Collect();

            var apiComponentPipeline = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ApiRouteAttributeName,
                    static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                    static (ctx, _) => ExtractComponentMetadata(ctx, "Api"))
                .Collect();

            // Combine all component pipelines
            var allComponents = pageComponentPipeline
                .Combine(layoutComponentPipeline)
                .Combine(apiComponentPipeline)
                .Select(static (tuple, _) =>
                {
                    var components = new List<ComponentModel>();
                    components.AddRange(tuple.Left.Left);
                    components.AddRange(tuple.Left.Right);
                    components.AddRange(tuple.Right);
                    return components;
                });

            // Step 4: Combine manifest + components and generate output
            var combined = manifestPipeline.Combine(allComponents);

            context.RegisterSourceOutput(combined, static (spc, source) =>
            {
                var (manifest, components) = source;

                try
                {
                    if (manifest == null)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.ManifestNotFound, Location.None));
                        return;
                    }

                    var routeCount = (manifest.Pages?.Count ?? 0)
                                   + (manifest.Layouts?.Count ?? 0)
                                   + (manifest.ApiRoutes?.Count ?? 0)
                                   + (manifest.ErrorPage != null ? 1 : 0);

                    if (routeCount == 0)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.ManifestEmpty, Location.None));
                        return;
                    }

                    // Report conflicts
                    if (manifest.Conflicts != null && manifest.Conflicts.Count > 0)
                    {
                        foreach (var conflict in manifest.Conflicts)
                        {
                            if (!string.IsNullOrEmpty(conflict.Message))
                            {
                                spc.ReportDiagnostic(Diagnostic.Create(
                                    DiagnosticDescriptors.RouteConflict,
                                    Location.None,
                                    conflict.Message,
                                    conflict.RoutePattern ?? "?"));
                            }
                        }
                    }

                    // Generate wrapper classes
                    var wrapperSource = WrapperEmitter.Emit(manifest, DefaultAppDir, GeneratedNamespace);

                    if (!string.IsNullOrEmpty(wrapperSource))
                    {
                        spc.AddSource("NextNet.Wrappers.g.cs",
                            SourceText.From(wrapperSource, Encoding.UTF8));
                    }

                    // Generate endpoint registration
                    var endpointSource = EndpointEmitter.Emit(manifest, DefaultAppDir, GeneratedNamespace);

                    if (!string.IsNullOrEmpty(endpointSource))
                    {
                        spc.AddSource("NextNet.Endpoints.g.cs",
                            SourceText.From(endpointSource, Encoding.UTF8));
                    }

                    // Generate API-specific endpoint registration (MapGet/MapPost/MapPut/MapPatch/MapDelete)
                    var apiEndpointSource = ApiEndpointEmitter.Emit(manifest, DefaultAppDir, GeneratedNamespace);

                    if (!string.IsNullOrEmpty(apiEndpointSource))
                    {
                        spc.AddSource("NextNet.ApiEndpoints.g.cs",
                            SourceText.From(apiEndpointSource, Encoding.UTF8));
                    }

                    // Generate DI registration
                    var diSource = DiEmitter.Emit(manifest, DefaultAppDir, GeneratedNamespace);

                    if (!string.IsNullOrEmpty(diSource))
                    {
                        spc.AddSource("NextNet.Services.g.cs",
                            SourceText.From(diSource, Encoding.UTF8));
                    }
                }
                catch (Exception ex)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InternalError,
                        Location.None,
                        ex.Message));
                }
            });
        }

        /// <summary>
        /// Checks whether the given file path is a routes.json manifest file.
        /// </summary>
        private static bool IsRoutesJsonFile(string path)
        {
            return !string.IsNullOrEmpty(path) &&
                   path.EndsWith("routes.json", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Extracts component metadata from a syntax node annotated with a marker attribute.
        /// Only extracts string data — never holds onto ISymbol or SyntaxNode references.
        /// </summary>
        private static ComponentModel ExtractComponentMetadata(
            GeneratorAttributeSyntaxContext ctx,
            string componentType)
        {
            try
            {
                if (ctx.TargetSymbol is INamedTypeSymbol typeSymbol)
                {
                    var typeName = typeSymbol.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat);

                    var filePath = ctx.TargetNode.SyntaxTree.FilePath;

                    var route = string.Empty;
                    if (ctx.Attributes.Length > 0)
                    {
                        var attr = ctx.Attributes[0];
                        if (attr?.NamedArguments.Length > 0)
                        {
                            foreach (var kvp in attr.NamedArguments)
                            {
                                if (string.Equals(kvp.Key, "Route", StringComparison.Ordinal) ||
                                    string.Equals(kvp.Key, "RoutePattern", StringComparison.Ordinal))
                                {
                                    route = kvp.Value.Value?.ToString() ?? string.Empty;
                                }
                            }
                        }
                    }

                    return new ComponentModel
                    {
                        TypeName = typeName,
                        FilePath = filePath,
                        RoutePattern = route,
                        ComponentType = componentType
                    };
                }
            }
            catch (Exception ex)
            {
                // Extraction failed — return default. Generator falls back to convention-based names.
                System.Diagnostics.Debug.WriteLine(
                    "[NextNet] Component metadata extraction error: " + ex.Message);
            }

            return new ComponentModel();
        }
    }
