using System;
using System.Collections.Generic;
using System.Text;
using NextNet.SourceGenerators.Models;
using NextNet.SourceGenerators.Utils;

namespace NextNet.SourceGenerators.Emitters
{
    /// <summary>
    /// Generates endpoint registration code (MapGet, MapPost, MapPut, MapPatch, MapDelete)
    /// for API route handlers. Each generated handler resolves the route class from DI,
    /// sets the HttpContext, and dispatches to the corresponding HTTP method.
    /// </summary>
    internal static class ApiEndpointEmitter
    {
        /// <summary>
        /// Emits the <c>RegisterApiEndpoints</c> extension method source code.
        /// </summary>
        /// <param name="manifest">The route manifest.</param>
        /// <param name="appDir">The application directory.</param>
        /// <param name="ns">The namespace for generated types.</param>
        /// <returns>A string containing the API endpoint registration extension method.</returns>
        public static string Emit(RouteManifestModel manifest, string appDir, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Builder;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Generated API route registration extensions for NextNet.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).AppendLine("public static class NextNetApiRouteRegistry");
            sb.Append(indent).AppendLine("{");

            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Registers all NextNet API route endpoints.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public static void RegisterApiEndpoints(")
              .Append("this global::Microsoft.AspNetCore.Builder.WebApplication app)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");

            if (manifest.ApiRoutes != null && manifest.ApiRoutes.Count > 0)
            {
                foreach (var api in manifest.ApiRoutes)
                {
                    if (string.IsNullOrEmpty(api.RoutePattern) || string.IsNullOrEmpty(api.FilePath))
                        continue;

                    EmitApiEndpoints(sb, api, appDir, ns, indent + "        ");
                }
            }
            else
            {
                sb.Append(indent).AppendLine("        // No API routes registered.");
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Generates MapGet/MapPost/MapPut/MapPatch/MapDelete calls for a single API route.
        /// Each generated handler resolves the route wrapper from DI, sets HttpContext,
        /// and dispatches to the corresponding PascalCase method on the route class.
        /// </summary>
        private static void EmitApiEndpoints(
            StringBuilder sb,
            RouteEntryModel api,
            string appDir,
            string ns,
            string indent)
        {
            var wrapperName = GetWrapperName(api, appDir);
            var routePattern = api.RoutePattern;

            // Determine which HTTP methods to generate
            var methodsToGenerate = (api.HttpMethods != null && api.HttpMethods.Count > 0)
                ? api.HttpMethods
                : new List<string> { "GET", "POST", "PUT", "PATCH", "DELETE" };

            foreach (var method in methodsToGenerate)
            {
                var mapMethod = GetMapMethod(method);
                if (mapMethod == null)
                    continue;

                var pascalMethod = GetPascalMethodName(method);
                if (pascalMethod == null)
                    continue;

                sb.Append(indent).AppendLine("/// <summary>");
                sb.Append(indent).Append("/// ").Append(method).Append(" ").AppendLine(routePattern);
                sb.Append(indent).AppendLine("/// </summary>");

                // Extract route parameters (e.g. {id} from /api/users/{id})
                var routeParams = IncrementalHelpers.ExtractRouteParameters(routePattern);

                // Build parameter list for the lambda
                var lambdaParams = new List<string>();
                foreach (var rp in routeParams)
                {
                    lambdaParams.Add("string " + rp);
                }
                lambdaParams.Add("HttpContext context");

                var signature = string.Join(", ", lambdaParams);

                sb.Append(indent).Append("app.").Append(mapMethod).Append("(\"")
                  .Append(routePattern).Append("\", ");
                sb.Append("async (").Append(signature).Append(") =>").AppendLine();
                sb.Append(indent).AppendLine("{");
                sb.Append(indent).Append("    var route = context.RequestServices")
                  .Append(".GetRequiredService<global::").Append(ns).Append(".")
                  .Append(wrapperName).AppendLine(">();");
                sb.Append(indent).AppendLine("    route.HttpContext = context;");

                // Pass route params to the method call
                if (routeParams.Count > 0)
                {
                    var args = string.Join(", ", routeParams);
                    sb.Append(indent).Append("    return await route.")
                      .Append(pascalMethod).Append("(").Append(args).AppendLine(");");
                }
                else
                {
                    sb.Append(indent).Append("    return await route.")
                      .Append(pascalMethod).AppendLine("();");
                }

                sb.Append(indent).AppendLine("});");
                sb.AppendLine();
            }
        }

        /// <summary>
        /// Maps an HTTP method name to the corresponding Minimal API extension method.
        /// </summary>
        private static string? GetMapMethod(string httpMethod)
        {
            return httpMethod.ToUpperInvariant() switch
            {
                "GET" => "MapGet",
                "POST" => "MapPost",
                "PUT" => "MapPut",
                "PATCH" => "MapPatch",
                "DELETE" => "MapDelete",
                _ => null
            };
        }

        /// <summary>
        /// Converts an uppercase HTTP method name to PascalCase for method invocation.
        /// "GET" -> "Get", "POST" -> "Post", etc.
        /// </summary>
        private static string? GetPascalMethodName(string httpMethod)
        {
            if (string.IsNullOrEmpty(httpMethod))
                return null;

            var upper = httpMethod.ToUpperInvariant();
            return upper switch
            {
                "GET" => "Get",
                "POST" => "Post",
                "PUT" => "Put",
                "PATCH" => "Patch",
                "DELETE" => "Delete",
                _ => null
            };
        }

        private static string GetWrapperName(RouteEntryModel entry, string appDir)
            => IncrementalHelpers.GetWrapperName(entry, appDir);
    }
}
