using System;
using System.Text;
using NextNet.SourceGenerators.Models;
using NextNet.SourceGenerators.Utils;

namespace NextNet.SourceGenerators.Emitters;
    /// <summary>
    /// Generates DI registration code (<c>AddTransient</c>/<c>AddScoped</c>) for all
    /// generated wrapper types so they can be resolved from the DI container.
    /// </summary>
    internal static class DiEmitter
    {
        /// <summary>
        /// Emits the <c>RegisterServices</c> extension method source code.
        /// </summary>
        /// <param name="manifest">The route manifest.</param>
        /// <param name="appDir">The application directory.</param>
        /// <param name="ns">The namespace for generated types.</param>
        /// <returns>A string containing the DI registration extension method.</returns>
        public static string Emit(RouteManifestModel manifest, string appDir, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Generated DI registration extensions for NextNet.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).AppendLine("public static class NextNetServiceRegistry");
            sb.Append(indent).AppendLine("{");

            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Registers all NextNet components in the DI container.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public static void RegisterServices(")
              .Append("this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");

            var count = 0;

            // Register page wrappers
            if (manifest.Pages != null)
            {
                foreach (var page in manifest.Pages)
                {
                    if (string.IsNullOrEmpty(page.FilePath))
                        continue;

                    var wrapperName = GetWrapperName(page, appDir);
                    sb.Append(indent).Append("        services.AddTransient<global::")
                      .Append(ns).Append(".").Append(wrapperName).AppendLine(">();");
                    count++;
                }
            }

            // Register layout wrappers
            if (manifest.Layouts != null)
            {
                foreach (var layout in manifest.Layouts)
                {
                    if (string.IsNullOrEmpty(layout.FilePath))
                        continue;

                    var wrapperName = GetWrapperName(layout, appDir);
                    sb.Append(indent).Append("        services.AddTransient<global::")
                      .Append(ns).Append(".").Append(wrapperName).AppendLine(">();");
                    count++;
                }
            }

            // Register API route wrappers (scoped per-request)
            if (manifest.ApiRoutes != null)
            {
                foreach (var api in manifest.ApiRoutes)
                {
                    if (string.IsNullOrEmpty(api.FilePath))
                        continue;

                    var wrapperName = GetWrapperName(api, appDir);
                    sb.Append(indent).Append("        services.AddScoped<global::")
                      .Append(ns).Append(".").Append(wrapperName).AppendLine(">();");
                    count++;
                }
            }

            // Register error page wrapper
            if (manifest.ErrorPage != null && !string.IsNullOrEmpty(manifest.ErrorPage.FilePath))
            {
                var wrapperName = GetWrapperName(manifest.ErrorPage, appDir);
                sb.Append(indent).Append("        services.AddTransient<global::")
                  .Append(ns).Append(".").Append(wrapperName).AppendLine(">();");
                count++;
            }

            if (count == 0)
            {
                sb.Append(indent).AppendLine("        // No routes registered.");
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string GetWrapperName(RouteEntryModel entry, string appDir)
            => IncrementalHelpers.GetWrapperName(entry, appDir);
    }
