using System;
using System.Collections.Generic;
using System.Text;
using NextNet.SourceGenerators.Models;
using NextNet.SourceGenerators.Utils;

namespace NextNet.SourceGenerators.Emitters;
    /// <summary>
    /// Generates endpoint registration code (MapGet, MapPost, Map) for all discovered routes.
    /// </summary>
    internal static class EndpointEmitter
    {
        /// <summary>
        /// Emits the <c>RegisterEndpoints</c> extension method source code.
        /// </summary>
        /// <param name="manifest">The route manifest.</param>
        /// <param name="appDir">The application directory.</param>
        /// <param name="ns">The namespace for generated types.</param>
        /// <returns>A string containing the endpoint registration extension method.</returns>
        public static string Emit(RouteManifestModel manifest, string appDir, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Builder;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using NextNet.Components;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Generated route registration extensions for NextNet.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).AppendLine("public static class NextNetRouteRegistry");
            sb.Append(indent).AppendLine("{");

            // RegisterEndpoints method
            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Registers all NextNet page, API, and error routes.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public static void RegisterEndpoints(")
              .Append("this global::Microsoft.AspNetCore.Builder.WebApplication app)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");

            // Emit page endpoints
            if (manifest.Pages != null)
            {
                foreach (var page in manifest.Pages)
                {
                    if (string.IsNullOrEmpty(page.RoutePattern) || string.IsNullOrEmpty(page.FilePath))
                        continue;

                    EmitPageEndpoint(sb, page, appDir, ns, indent + "        ");
                }
            }

            // Emit API route endpoints
            if (manifest.ApiRoutes != null)
            {
                foreach (var api in manifest.ApiRoutes)
                {
                    if (string.IsNullOrEmpty(api.RoutePattern) || string.IsNullOrEmpty(api.FilePath))
                        continue;

                    EmitApiEndpoint(sb, api, appDir, ns, indent + "        ");
                }
            }

            // Emit error page (catch-all)
            if (manifest.ErrorPage != null && !string.IsNullOrEmpty(manifest.ErrorPage.FilePath))
            {
                EmitErrorEndpoint(sb, manifest.ErrorPage, appDir, ns, indent + "        ");
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitPageEndpoint(
            StringBuilder sb,
            RouteEntryModel page,
            string appDir,
            string ns,
            string indent)
        {
            var wrapperName = GetWrapperName(page, appDir);
            var routeParams = IncrementalHelpers.ExtractRouteParameters(page.RoutePattern);
            var hasParams = routeParams.Count > 0;
            var hasCatchAll = IncrementalHelpers.HasCatchAll(page.RoutePattern);

            // Build method signature
            var paramList = new List<string>();
            foreach (var p in routeParams)
            {
                paramList.Add("string " + p);
            }

            var signature = string.Join(", ", paramList);

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).Append("/// Page: ").AppendLine(page.RoutePattern);
            sb.Append(indent).AppendLine("/// </summary>");

            // Use MapGet for pages; always async because Render() returns Task<IHtmlContent>
            if (hasCatchAll)
            {
                // Catch-all uses Map (not MapGet) for full path capture
                sb.Append(indent).Append("app.Map(\"")
                  .Append(page.RoutePattern).Append("\", ");
                sb.Append("async (").Append(signature).Append(") =>").AppendLine();
            }
            else
            {
                sb.Append(indent).Append("app.MapGet(\"")
                  .Append(page.RoutePattern).Append("\", ");
                sb.Append("async (").Append(signature).Append(") =>").AppendLine();
            }

            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    var page = new global::")
              .Append(ns).Append(".").Append(wrapperName).AppendLine("();");
            sb.Append(indent).Append("    var html = await page.Render();")
              .AppendLine();
            sb.Append(indent).Append("    return Results.Content(html.ToHtml(), \"text/html\");")
              .AppendLine();
            sb.Append(indent).AppendLine("});");
            sb.AppendLine();
        }

        private static void EmitApiEndpoint(
            StringBuilder sb,
            RouteEntryModel api,
            string appDir,
            string ns,
            string indent)
        {
            var wrapperName = GetWrapperName(api, appDir);

            // API routes generate both GET and POST
            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).Append("/// API: ").AppendLine(api.RoutePattern);
            sb.Append(indent).AppendLine("/// </summary>");

            // GET endpoint
            sb.Append(indent).Append("app.MapGet(\"")
              .Append(api.RoutePattern).Append("\", ")
              .Append("async (HttpContext context) =>").AppendLine();
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    var route = new global::")
              .Append(ns).Append(".").Append(wrapperName).AppendLine("();");
            sb.Append(indent).AppendLine("    return await route.Handle(context);");
            sb.Append(indent).AppendLine("});");
            sb.AppendLine();

            // POST endpoint
            sb.Append(indent).Append("app.MapPost(\"")
              .Append(api.RoutePattern).Append("\", ")
              .Append("async (HttpContext context) =>").AppendLine();
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    var route = new global::")
              .Append(ns).Append(".").Append(wrapperName).AppendLine("();");
            sb.Append(indent).AppendLine("    return await route.Handle(context);");
            sb.Append(indent).AppendLine("});");
            sb.AppendLine();
        }

        private static void EmitErrorEndpoint(
            StringBuilder sb,
            RouteEntryModel error,
            string appDir,
            string ns,
            string indent)
        {
            var wrapperName = GetWrapperName(error, appDir);

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Error page (catch-all fallback).");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("app.Map(\"/{*path}\", ")
              .Append("async (string path) =>").AppendLine();
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    var page = new global::")
              .Append(ns).Append(".").Append(wrapperName).AppendLine("();");
            sb.Append(indent).Append("    var html = await page.Render();")
              .AppendLine();
            sb.Append(indent).Append("    return Results.Content(html.ToHtml(), \"text/html\");")
              .AppendLine();
            sb.Append(indent).AppendLine("});");
            sb.AppendLine();
        }

        private static string GetWrapperName(RouteEntryModel entry, string appDir)
            => IncrementalHelpers.GetWrapperName(entry, appDir);
    }
