using System;
using System.Collections.Generic;
using System.Text;
using NextNet.SourceGenerators.Models;
using NextNet.SourceGenerators.Utils;

namespace NextNet.SourceGenerators.Emitters;
    /// <summary>
    /// Generates wrapper classes that delegate to user-implemented page/layout/route types.
    /// Each wrapper implements the corresponding NextNet interface (IPage, ILayout, etc.)
    /// and instantiates the user's type via a <c>global::</c> reference.
    /// </summary>
    internal static class WrapperEmitter
    {
        /// <summary>
        /// Emits wrapper class source code for all route entries.
        /// </summary>
        /// <param name="manifest">The route manifest.</param>
        /// <param name="appDir">The application directory (e.g. "app/").</param>
        /// <param name="ns">The namespace for generated types.</param>
        /// <returns>A string containing all wrapper class definitions.</returns>
        public static string Emit(RouteManifestModel manifest, string appDir, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using NextNet.Components;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var wrapperIndex = 0;

            // Emit page wrappers
            if (manifest.Pages != null)
            {
                foreach (var page in manifest.Pages)
                {
                    if (string.IsNullOrEmpty(page.RoutePattern) || string.IsNullOrEmpty(page.FilePath))
                        continue;

                    var wrapperName = GetWrapperClassName(page, appDir, ref wrapperIndex);
                    var userTypeName = IncrementalHelpers.FilePathToTypeName(page.FilePath, appDir);
                    var routeParams = IncrementalHelpers.ExtractRouteParameters(page.RoutePattern);

                    EmitPageWrapper(sb, wrapperName, userTypeName, page.RoutePattern, routeParams, ns);
                }
            }

            // Emit layout wrappers
            if (manifest.Layouts != null)
            {
                foreach (var layout in manifest.Layouts)
                {
                    if (string.IsNullOrEmpty(layout.RoutePattern) || string.IsNullOrEmpty(layout.FilePath))
                        continue;

                    var wrapperName = GetWrapperClassName(layout, appDir, ref wrapperIndex);
                    var userTypeName = IncrementalHelpers.FilePathToTypeName(layout.FilePath, appDir);

                    EmitLayoutWrapper(sb, wrapperName, userTypeName, layout.RoutePattern, ns);
                }
            }

            // Emit API route wrappers
            if (manifest.ApiRoutes != null)
            {
                foreach (var api in manifest.ApiRoutes)
                {
                    if (string.IsNullOrEmpty(api.RoutePattern) || string.IsNullOrEmpty(api.FilePath))
                        continue;

                    var wrapperName = GetWrapperClassName(api, appDir, ref wrapperIndex);
                    var userTypeName = IncrementalHelpers.FilePathToTypeName(api.FilePath, appDir);

                    EmitApiRouteWrapper(sb, wrapperName, userTypeName, api.RoutePattern, ns);
                }
            }

            // Emit error page wrapper
            if (manifest.ErrorPage != null && !string.IsNullOrEmpty(manifest.ErrorPage.FilePath))
            {
                var wrapperName = GetWrapperClassName(manifest.ErrorPage, appDir, ref wrapperIndex);
                var userTypeName = IncrementalHelpers.FilePathToTypeName(manifest.ErrorPage.FilePath, appDir);

                EmitErrorPageWrapper(sb, wrapperName, userTypeName, ns);
            }

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string GetWrapperClassName(RouteEntryModel entry, string appDir, ref int index)
        {
            var baseName = IncrementalHelpers.FilePathToTypeName(entry.FilePath, appDir);
            if (!string.IsNullOrEmpty(baseName) && baseName != "Unknown" && baseName != "UnknownPage")
            {
                return "NextNet_" + baseName;
            }

            // Fallback: use an index-based name
            index++;
            return "NextNet_Route_" + index;
        }

        private static void EmitPageWrapper(
            StringBuilder sb,
            string wrapperName,
            string userTypeName,
            string routePattern,
            List<string> routeParams,
            string ns)
        {
            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).Append("/// Generated wrapper for route: ").AppendLine(routePattern);
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("public sealed class ").Append(wrapperName)
              .AppendLine(" : global::NextNet.Components.IPage");
            sb.Append(indent).AppendLine("{");

            // Render method
            sb.Append(indent).Append("    public async global::System.Threading.Tasks.Task<")
              .Append("global::NextNet.Components.IHtmlContent> Render()")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        var inner = new global::")
              .Append(userTypeName).AppendLine("();");

            // Set route parameters as properties
            foreach (var param in routeParams)
            {
                if (!string.IsNullOrEmpty(param))
                {
                    var propName = Capitalize(param);
                    sb.Append(indent).Append("        inner.")
                      .Append(propName).Append(" = ").Append(param).AppendLine(";");
                }
            }

            sb.Append(indent).AppendLine("        return await inner.Render();");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine();

            // Props property
            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Route parameters and metadata for this page.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public global::System.Collections.Generic")
              .Append(".IReadOnlyDictionary<string, object> Props { get; }")
              .AppendLine();
            sb.Append(indent).Append("        = new global::System.Collections.Generic")
              .Append(".Dictionary<string, object>();")
              .AppendLine();

            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitLayoutWrapper(
            StringBuilder sb,
            string wrapperName,
            string userTypeName,
            string routePattern,
            string ns)
        {
            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).Append("/// Generated wrapper for layout: ").AppendLine(routePattern);
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("public sealed class ").Append(wrapperName)
              .AppendLine(" : global::NextNet.Components.ILayout");
            sb.Append(indent).AppendLine("{");

            // Render method with children
            sb.Append(indent).Append("    public async global::System.Threading.Tasks.Task<")
              .Append("global::NextNet.Components.IHtmlContent> Render(")
              .Append("global::NextNet.Components.IHtmlContent children)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        var inner = new global::")
              .Append(userTypeName).AppendLine("();");
            sb.Append(indent).AppendLine("        return await inner.Render(children);");
            sb.Append(indent).AppendLine("    }");

            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitApiRouteWrapper(
            StringBuilder sb,
            string wrapperName,
            string userTypeName,
            string routePattern,
            string ns)
        {
            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).Append("/// Generated wrapper for API route: ").AppendLine(routePattern);
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("public sealed class ").Append(wrapperName)
              .AppendLine(" : global::NextNet.Components.ApiRoute");
            sb.Append(indent).AppendLine("{");

            // Handle method
            sb.Append(indent).Append("    public override async global::System.Threading.Tasks.Task<")
              .Append("Microsoft.AspNetCore.Http.IResult> Handle(")
              .Append("Microsoft.AspNetCore.Http.HttpContext context)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        var inner = new global::")
              .Append(userTypeName).AppendLine("();");
            sb.Append(indent).AppendLine("        inner.HttpContext = context;");
            sb.Append(indent).AppendLine("        return await inner.Handle(context);");
            sb.Append(indent).AppendLine("    }");

            // Get method
            EmitApiRouteMethodOverride(sb, indent, "Get", userTypeName);
            // Post method
            EmitApiRouteMethodOverride(sb, indent, "Post", userTypeName);
            // Put method
            EmitApiRouteMethodOverride(sb, indent, "Put", userTypeName);
            // Patch method
            EmitApiRouteMethodOverride(sb, indent, "Patch", userTypeName);
            // Delete method
            EmitApiRouteMethodOverride(sb, indent, "Delete", userTypeName);

            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitApiRouteMethodOverride(
            StringBuilder sb,
            string indent,
            string methodName,
            string userTypeName)
        {
            sb.Append(indent).Append("    public override async global::System.Threading.Tasks.Task<")
              .Append("Microsoft.AspNetCore.Http.IResult> ")
              .Append(methodName).AppendLine("()");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        var inner = new global::")
              .Append(userTypeName).AppendLine("();");
            sb.Append(indent).AppendLine("        inner.HttpContext = HttpContext;");
            sb.Append(indent).Append("        return await inner.").Append(methodName).AppendLine("();");
            sb.Append(indent).AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitErrorPageWrapper(
            StringBuilder sb,
            string wrapperName,
            string userTypeName,
            string ns)
        {
            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Generated wrapper for error page.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("public sealed class ").Append(wrapperName)
              .AppendLine(" : global::NextNet.Components.IErrorPage");
            sb.Append(indent).AppendLine("{");

            // Render method with exception
            sb.Append(indent).Append("    public async global::System.Threading.Tasks.Task<")
              .Append("global::NextNet.Components.IHtmlContent> Render(")
              .Append("global::System.Exception exception)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        var inner = new global::")
              .Append(userTypeName).AppendLine("();");
            sb.Append(indent).AppendLine("        return await inner.Render(exception);");
            sb.Append(indent).AppendLine("    }");

            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Capitalizes the first character of a string.
        /// </summary>
        private static string Capitalize(string input)
        {
            if (string.IsNullOrEmpty(input))
                return input;
            return char.ToUpper(input[0]) + input.Substring(1);
        }
    }
