using System.Collections.Concurrent;
using System.Linq;
using System.Reflection;
using NextNet.Components;
using NextNet.Logging;
using NextNet.Routing;

namespace NextNet.Rendering;

/// <summary>
/// Default <see cref="IRouteComponentResolver"/> that resolves page and layout types
/// by scanning assemblies for types implementing <see cref="IPage"/> and <see cref="ILayout"/>.
/// Matches file paths to type names via configurable conventions.
/// </summary>
/// <example>
/// <code>
/// // Default usage — scans all loaded assemblies:
/// var resolver = new ConventionRouteComponentResolver();
///
/// // Provide explicit type mappings for testing:
/// var resolver = new ConventionRouteComponentResolver(
///     new Dictionary&lt;string, Type&gt; { ["app/page.cs"] = typeof(MyPage) },
///     new Dictionary&lt;string, Type&gt; { ["app/layout.cs"] = typeof(MyLayout) });
/// </code>
/// </example>
public sealed class ConventionRouteComponentResolver : IRouteComponentResolver
{
    private readonly IReadOnlyDictionary<string, Type> _pageMap;
    private readonly IReadOnlyDictionary<string, Type> _layoutMap;
    private readonly INextNetLogger? _logger;

    /// <summary>
    /// Initializes a new instance that scans the specified assemblies.
    /// </summary>
    /// <param name="assemblies">The assemblies to scan for components. If empty, scans all loaded assemblies.</param>
    /// <param name="logger">Optional logger.</param>
    public ConventionRouteComponentResolver(IEnumerable<Assembly>? assemblies = null, INextNetLogger? logger = null)
    {
        _logger = logger;
        var targets = assemblies?.ToList();
        if (targets == null || targets.Count == 0)
        {
            targets = AppDomain.CurrentDomain.GetAssemblies().ToList();
        }

        var pageMap = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);
        var layoutMap = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);

        foreach (var asm in targets)
        {
            // Skip dynamic assemblies (e.g. generated by Castle.Core/Moq).
            // They are volatile during parallel execution and cannot contain
            // our IPage/ILayout components.
            if (asm.IsDynamic)
            {
                _logger?.Debug("Skipping dynamic assembly: {Assembly}", asm.FullName);
                continue;
            }

            Type[] exportedTypes;
            try
            {
                exportedTypes = asm.GetExportedTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                // Some assemblies may have loader exceptions for some types.
                // Load the types that can be loaded and log the failures.
                _logger?.Warn("ReflectionTypeLoadException loading types from {Assembly}: {Count} loader exceptions",
                    asm.FullName, ex.LoaderExceptions?.Length ?? 0);
                exportedTypes = ex.Types.Where(t => t != null).Cast<Type>().ToArray();
            }
            catch (TypeLoadException ex)
            {
                // Dynamic proxy assemblies (Castle.Core DynamicProxyGenAssembly2)
                // can throw TypeLoadException when accessed concurrently by parallel
                // test runs. Safely skip the assembly.
                _logger?.Warn("TypeLoadException loading types from {Assembly}: {Message}",
                    asm.FullName, ex.Message);
                continue;
            }

            foreach (var type in exportedTypes)
            {
                if (typeof(IPage).IsAssignableFrom(type) && !type.IsAbstract)
                {
                    // Derive a file-path key from the type's full name
                    var key = TypeNameToFilePath(type.FullName ?? type.Name);
                    if (!pageMap.ContainsKey(key))
                    {
                        pageMap[key] = type;
                        _logger?.Debug("Mapped page type {TypeName} -> {Key}", type.FullName, key);
                    }
                }

                if (typeof(ILayout).IsAssignableFrom(type) && !type.IsAbstract)
                {
                    var key = TypeNameToFilePath(type.FullName ?? type.Name);
                    if (!layoutMap.ContainsKey(key))
                    {
                        layoutMap[key] = type;
                        _logger?.Debug("Mapped layout type {TypeName} -> {Key}", type.FullName, key);
                    }
                }
            }
        }

        _pageMap = pageMap;
        _layoutMap = layoutMap;

        _logger?.Info("Resolved {PageCount} page types and {LayoutCount} layout types.",
            _pageMap.Count, _layoutMap.Count);
    }

    /// <summary>
    /// Creates a resolver from explicit type mappings (useful in tests).
    /// </summary>
    public ConventionRouteComponentResolver(
        IReadOnlyDictionary<string, Type> pageMap,
        IReadOnlyDictionary<string, Type> layoutMap,
        INextNetLogger? logger = null)
    {
        _pageMap = pageMap ?? throw new ArgumentNullException(nameof(pageMap));
        _layoutMap = layoutMap ?? throw new ArgumentNullException(nameof(layoutMap));
        _logger = logger;
    }

    /// <inheritdoc />
    public Type? GetPageType(RouteEntry entry)
    {
        var key = NormalizePath(entry.FilePath);
        if (_pageMap.TryGetValue(key, out var type))
            return type;

        _logger?.Warn("No page type found for route {RoutePattern} at {FilePath}", entry.RoutePattern, entry.FilePath);
        return null;
    }

    /// <inheritdoc />
    public Type? GetLayoutType(string layoutPath)
    {
        var key = NormalizePath(layoutPath);
        if (_layoutMap.TryGetValue(key, out var type))
            return type;

        _logger?.Warn("No layout type found for {LayoutPath}", layoutPath);
        return null;
    }

    private static string NormalizePath(string path)
    {
        // Normalize directory separators and remove leading/trailing slashes
        return path.Replace('\\', '/').Trim('/');
    }

    private static string TypeNameToFilePath(string typeName)
    {
        // Convert "MyApp.Pages.About" to "pages/about" (lowercase, dots become slashes)
        var parts = typeName.Split('.');
        // Remove the root namespace prefix (assume it's the assembly name or first segment)
        var segments = new List<string>();
        foreach (var part in parts)
        {
            if (segments.Count == 0)
            {
                // Skip the root namespace
                segments.Add(part.ToLowerInvariant());
            }
            else
            {
                segments.Add(part.ToLowerInvariant());
            }
        }

        // Convert PascalCase to kebab-case for individual segments
        for (int i = 0; i < segments.Count; i++)
        {
            segments[i] = PascalToKebab(segments[i]);
        }

        // Remove trailing "page" or "layout" if present (they're part of the convention)
        // Actually keep them — the file path is like "app/page.cs", "app/about/page.cs"
        return string.Join("/", segments);
    }

    private static string PascalToKebab(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;

        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < input.Length; i++)
        {
            if (i > 0 && char.IsUpper(input[i]))
            {
                sb.Append('-');
            }
            sb.Append(char.ToLowerInvariant(input[i]));
        }
        return sb.ToString();
    }
}
