using NextNet.Data.Abstractions.Abstractions;
using NextNet.Data.Abstractions.Models;

namespace NextNet.Data.Abstractions.Internal;

/// <summary>
/// Provider-agnostic scaffold provider that generates model classes only.
/// Used when no data provider has been configured in the project.
/// Returns errors for repository and CRUD generation since those require
/// a specific data provider.
/// </summary>
/// <remarks>
/// <para>
/// This provider generates simple POCO model classes without any provider-specific
/// attributes. It is useful for projects that are in early development stages or
/// that do not use a database provider yet.
/// </para>
/// </remarks>
internal sealed class ModelOnlyScaffoldProvider : IScaffoldProvider
{
    /// <inheritdoc />
    public string ProviderName => "ModelOnly";

    /// <inheritdoc />
    public Task<ScaffoldArtifact> GenerateModelAsync(
        string entityName,
        ScaffoldOptions options,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(entityName))
            throw new ArgumentNullException(nameof(entityName));

        var ns = TemplateEngine.ResolveNamespace(options.ModelsNamespace, options.ProjectNamespace);
        var pluralName = TemplateEngine.Pluralize(entityName);
        var camelName = char.ToLowerInvariant(entityName[0]) + entityName[1..];
        var keyType = DetermineKeyType(options.Properties);

        var propertyDeclarations = BuildPropertyDeclarations(options.Properties);

        var content = $@"// <auto-generated />
// Generated by NextNet Scaffolding v1.0.0 on {DateTime.Now:yyyy-MM-dd}
// Entity: {entityName}

using System;
using System.ComponentModel.DataAnnotations;

namespace {ns};

/// <summary>
/// Represents a {entityName} entity.
/// </summary>
public class {entityName}
{{
    /// <summary>
    /// Gets or sets the unique identifier for this {entityName}.
    /// </summary>
    [Key]
    public {keyType} Id {{ get; set; }}{propertyDeclarations}
}}
";
        var lines = TemplateEngine.CountLines(content);
        var outputDir = Path.GetFullPath(Path.Combine(options.OutputDirectory, options.ModelsDirectory));
        var filePath = Path.Combine(outputDir, $"{entityName}.cs");
        var relativePath = Path.Combine(options.ModelsDirectory, $"{entityName}.cs");

        var wasSkipped = TemplateEngine.WriteOrSkip(filePath, content, options.DryRun, options.OverwriteExisting);

        var artifact = new ScaffoldArtifact(
            FilePath: filePath,
            RelativePath: relativePath,
            ArtifactType: ScaffoldArtifactType.Model,
            EntityName: entityName,
            LinesOfCode: lines,
            WasSkipped: wasSkipped);

        return Task.FromResult(artifact);
    }

    /// <inheritdoc />
    public Task<ScaffoldArtifact> GenerateRepositoryAsync(
        string entityName,
        ScaffoldOptions options,
        CancellationToken cancellationToken = default)
    {
        var relativePath = Path.Combine(options.RepositoriesDirectory, $"{entityName}Repository.cs");
        var filePath = Path.GetFullPath(Path.Combine(options.OutputDirectory, relativePath));

        return Task.FromResult(new ScaffoldArtifact(
            FilePath: filePath,
            RelativePath: relativePath,
            ArtifactType: ScaffoldArtifactType.Repository,
            EntityName: entityName,
            LinesOfCode: 0,
            WasSkipped: false,
            ErrorMessage: "No data provider configured. Run 'nextnet add data <provider>' first to enable provider-specific generation."));
    }

    /// <inheritdoc />
    public Task<ScaffoldArtifact[]> GenerateCrudAsync(
        string entityName,
        ScaffoldOptions options,
        CancellationToken cancellationToken = default)
    {
        var result = new[]
        {
            new ScaffoldArtifact(
                FilePath: "",
                RelativePath: "",
                ArtifactType: ScaffoldArtifactType.Action,
                EntityName: entityName,
                LinesOfCode: 0,
                WasSkipped: false,
                ErrorMessage: "No data provider configured. Run 'nextnet add data <provider>' first to enable CRUD generation.")
        };

        return Task.FromResult(result);
    }

    private static string DetermineKeyType(IReadOnlyList<ScaffoldProperty>? properties)
    {
        if (properties is not null)
        {
            foreach (var prop in properties)
            {
                if (prop.IsKey)
                    return prop.Type;
            }
        }
        return "int";
    }

    internal static string BuildPropertyDeclarations(IReadOnlyList<ScaffoldProperty>? properties)
    {
        if (properties is null || properties.Count == 0)
            return string.Empty;

        var sb = new System.Text.StringBuilder();
        foreach (var prop in properties)
        {
            if (prop.IsKey)
                continue; // Skip key since we already generate Id

            var typeSuffix = prop.IsRequired ? string.Empty : "?";
            var typeName = prop.Type + typeSuffix;

            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Gets or sets the {prop.Name}.");
            sb.AppendLine("    /// </summary>");

            if (prop.IsRequired)
                sb.AppendLine("    [Required]");
            if (prop.MaxLength.HasValue)
                sb.AppendLine($"    [MaxLength({prop.MaxLength.Value})]");

            sb.AppendLine($"    public {typeName} {prop.Name} {{ get; set; }}");
        }
        return sb.ToString();
    }
}
