using System.Reflection;
using Xunit;

namespace NextNet.Architecture.Tests;

/// <summary>
/// Architecture invariant tests ensuring data models follow the sealed record convention.
/// </summary>
public class DataModelConventionTests
{
    private readonly Assembly _dataAbstractionsAssembly = typeof(NextNet.Data.Abstractions.Abstractions.IDataProvider).Assembly;

    /// <summary>
    /// All data model types in NextNet.Data.Abstractions.Models must be sealed records.
    /// </summary>
    [Fact]
    public void DataModels_Should_BeSealedRecords()
    {
        // Arrange
        var modelTypes = _dataAbstractionsAssembly.GetExportedTypes()
            .Where(t => t.Namespace == "NextNet.Data.Abstractions.Models" && t.IsPublic)
            .ToList();

        Assert.NotEmpty(modelTypes);

        var nonSealedRecords = new List<string>();

        // Act
        foreach (var type in modelTypes)
        {
            // Skip enums — they are value types and not expected to be records
            if (type.IsEnum)
                continue;

            if (!type.IsSealed || !type.IsRecordType())
            {
                nonSealedRecords.Add($"{type.FullName} (IsSealed={type.IsSealed}, IsRecord={type.IsRecordType()})");
            }
        }

        // Assert
        Assert.Empty(nonSealedRecords);
    }

    /// <summary>
    /// All configuration model records in NextNet.Data.Abstractions.Configuration must be sealed
    /// records with immutable properties. This enforces the convention that configuration types are
    /// immutable value objects. Non-record types like validators and helpers in the same namespace
    /// are excluded from this check.
    /// </summary>
    [Fact]
    public void ConfigurationRecords_Should_BeImmutable()
    {
        // Arrange
        var configTypes = _dataAbstractionsAssembly.GetExportedTypes()
            .Where(t => t.Namespace == "NextNet.Data.Abstractions.Configuration" && t.IsPublic)
            .ToList();

        Assert.NotEmpty(configTypes);

        var nonSealedRecords = new List<string>();

        // Act
        foreach (var type in configTypes)
        {
            if (type.IsEnum)
                continue;

            // Only enforce the sealed record convention on types whose names end with
            // "Config" or "Options", which represent configuration models. Other types
            // in the namespace (e.g., validators like DataConfigValidator) are not
            // data models and should not be constrained.
            if (!type.Name.EndsWith("Config", StringComparison.Ordinal) &&
                !type.Name.EndsWith("Options", StringComparison.Ordinal))
                continue;

            if (!type.IsSealed || !type.IsRecordType())
            {
                nonSealedRecords.Add($"{type.FullName} (IsSealed={type.IsSealed}, IsRecord={type.IsRecordType()})");
            }
        }

        // Assert
        Assert.Empty(nonSealedRecords);
    }
}

/// <summary>
/// Extension methods for type inspection.
/// </summary>
internal static class TypeExtensions
{
    /// <summary>
    /// Determines whether the specified type is a record type.
    /// Records are identified by the presence of the compiler-generated
    /// &lt;Clone&gt;$ method added by the C# compiler for record types.
    /// This implementation works with .NET 6+ by checking for record-specific characteristics.
    /// </summary>
    public static bool IsRecordType(this Type type)
    {
        // Records have a <Clone>$ method generated by the compiler
        return type.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
            .Any(m => m.Name == "<Clone>$");
    }
}
