namespace NextNet.Data.EntityFramework.Internal;

/// <summary>
/// Contains embedded string templates for scaffold code generation.
/// </summary>
/// <remarks>
/// <para>
/// These templates are used by <see cref="EfCoreScaffoldProvider"/> to generate
/// model classes, repository classes, and CRUD page files.
/// </para>
/// <para>
/// Templates use <c>{placeholder}</c> syntax for variable substitution.
/// </para>
/// </remarks>
internal static class ScaffoldTemplates
{
    /// <summary>
    /// Template for a model class file.
    /// </summary>
    public const string ModelTemplate = @"// <auto-generated />
// Generated by NextNet.Data.EntityFramework scaffolder

namespace {Namespace};

/// <summary>
/// Represents a {ModelName} entity.
/// </summary>
public sealed class {ModelName}
{{
    /// <summary>
    /// Gets or sets the primary key.
    /// </summary>
    public int Id {{ get; set; }}

    /// <summary>
    /// Gets or sets the name.
    /// </summary>
    public string? Name {{ get; set; }}
}}
";

    /// <summary>
    /// Template for a repository class file.
    /// </summary>
    public const string RepositoryTemplate = @"// <auto-generated />
// Generated by NextNet.Data.EntityFramework scaffolder
// To regenerate: `nextnet generate repository {ModelName}`

using NextNet.Data.EntityFramework;
using {ModelsNamespace};

namespace {RepositoriesNamespace};

/// <summary>
/// Repository for {ModelName} entity operations.
/// </summary>
public sealed class {ModelName}Repository : EfCoreRepository<{ModelName}>
{{
    /// <summary>
    /// Initializes a new instance of the <see cref=""{ModelName}Repository""/> class.
    /// </summary>
    /// <param name=""contextFactory"">The DbContext factory.</param>
    public {ModelName}Repository(IDbContextFactory<AppDbContext> contextFactory)
        : base(contextFactory)
    {{
    }}
}}
";
}
