namespace NextNet.Data.Dapper;

/// <summary>
/// Options for configuring the behavior of <see cref="DapperRepository{T}"/>.
/// Controls table mapping, column resolution, schema, command timeout,
/// pagination dialect, and primary key behavior.
/// </summary>
/// <remarks>
/// <para>
/// These options are used by <see cref="DapperRepository{T}"/> and
/// <see cref="Internal.EntityMetadata"/> when generating SQL queries
/// and resolving entity-to-table mappings.
/// </para>
/// <para>
/// Default values assume SQL Server conventions. Override properties
/// to customize for PostgreSQL, MySQL, SQLite, or other databases.
/// </para>
/// <example>
/// <code>
/// var options = new DapperRepositoryOptions
/// {
///     TableName = "Users",
///     SchemaName = "identity",
///     KeyColumn = "UserId",
///     KeyIsAutoGenerated = true,
///     PaginationStyle = PaginationStyle.LimitOffset,
///     UseColumnAttribute = true,
///     CommandTimeout = 60
/// };
/// </code>
/// </example>
/// </remarks>
public sealed record DapperRepositoryOptions
{
    /// <summary>
    /// Gets or sets whether to respect <c>[Column("name")]</c> attributes
    /// on entity properties when resolving column names.
    /// Defaults to <c>true</c>.
    /// When <c>false</c>, the property name is used directly as the column name.
    /// </summary>
    public bool UseColumnAttribute { get; set; } = true;

    /// <summary>
    /// Gets or sets the default schema name for the table.
    /// Defaults to <c>"dbo"</c>. Use <c>null</c> or empty to omit schema prefix.
    /// This value is used when <see cref="Schema"/> is not explicitly set.
    /// </summary>
    public string SchemaName { get; set; } = "dbo";

    /// <summary>
    /// Gets or sets the default command timeout in seconds for all queries
    /// executed by the repository. Defaults to 30.
    /// </summary>
    public int CommandTimeout { get; set; } = 30;

    /// <summary>
    /// Gets or sets the table name for the entity. If not set, inferred from
    /// the <c>[Table]</c> attribute or the entity type name (pluralized).
    /// </summary>
    public string? TableName { get; set; }

    /// <summary>
    /// Gets or sets the schema name for the table. Overrides <see cref="SchemaName"/>
    /// when explicitly set. Use <c>null</c> or empty to fall back to <see cref="SchemaName"/>.
    /// </summary>
    public string? Schema { get; set; }

    /// <summary>
    /// Gets or sets the name of the primary key column. Defaults to <c>"Id"</c>.
    /// </summary>
    public string KeyColumn { get; set; } = "Id";

    /// <summary>
    /// Gets or sets whether the key is auto-generated (identity/auto-increment).
    /// Defaults to <c>true</c>. When true, insert queries append <c>SELECT CAST(SCOPE_IDENTITY() AS INT)</c>.
    /// </summary>
    public bool KeyIsAutoGenerated { get; set; } = true;

    /// <summary>
    /// Gets or sets the pagination SQL style. Defaults to <see cref="PaginationStyle.OffsetFetch"/>
    /// (SQL Server compatible). Set to <see cref="PaginationStyle.LimitOffset"/> for
    /// PostgreSQL, SQLite, or MySQL.
    /// </summary>
    public PaginationStyle PaginationStyle { get; set; } = PaginationStyle.OffsetFetch;

    /// <summary>
    /// Gets or sets the set of property/column names to exclude from INSERT and UPDATE queries.
    /// Typically includes computed columns, timestamps managed by the database, etc.
    /// </summary>
    public IReadOnlySet<string>? ExcludedColumns { get; set; }
}

/// <summary>
/// Defines the pagination SQL syntax used by <see cref="DapperRepository{T}"/>.
/// </summary>
public enum PaginationStyle
{
    /// <summary>Uses <c>OFFSET n ROWS FETCH NEXT n ROWS ONLY</c> (SQL Server).</summary>
    OffsetFetch,

    /// <summary>Uses <c>LIMIT n OFFSET n</c> (PostgreSQL, SQLite, MySQL).</summary>
    LimitOffset
}
