namespace NextNet.Data.EntityFramework;

/// <summary>
/// Application-level DbContext generated by NextNet.
/// Contains <see cref="DbSet{TEntity}"/> properties for all registered entity types.
/// </summary>
/// <remarks>
/// <para>
/// This class is auto-generated and extensible. Hand-written partial methods
/// in <c>AppDbContext.partial.cs</c> are preserved across regeneration.
/// </para>
/// <para>
/// Configured via <see cref="EfCoreOptions"/> during <c>UseEntityFramework()</c>.
/// </para>
/// </remarks>
public partial class AppDbContext : DbContext
{
    /// <summary>
    /// Initializes a new instance of <see cref="AppDbContext"/> with the specified options.
    /// </summary>
    /// <param name="options">The DbContext options for this context instance.</param>
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    /// <summary>
    /// Configures the entity models and relationships.
    /// Calls <c>modelBuilder.ApplyConfigurationsFromAssembly()</c> for discovered entity configurations.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    /// <remarks>
    /// Override this method in a partial class to add custom entity configurations.
    /// </remarks>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Apply configurations from all configured assemblies
        var assemblies = EntityConfigurationAssemblies;
        if (assemblies is not null)
        {
            foreach (var assembly in assemblies)
            {
                modelBuilder.ApplyConfigurationsFromAssembly(assembly);
            }
        }

        base.OnModelCreating(modelBuilder);
    }

    /// <summary>
    /// Gets or sets the assemblies to scan for entity type configurations.
    /// Set automatically during <c>UseEntityFramework()</c> registration.
    /// </summary>
    internal static IReadOnlyList<Assembly>? EntityConfigurationAssemblies { get; set; }
}
