using System.Text;
using NextNet.ServerActions.Results;
using NextNet.ServerActions.ServerActions;

namespace NextNet.ServerActions.Client;

/// <summary>
/// Generates C# client proxy source code for calling server actions via HttpClient.
/// The generated code provides a type-safe way to invoke server actions from client applications.
/// </summary>
public sealed class ServerActionClientProxyGenerator
{
    private readonly string _baseUrl;

    /// <summary>
    /// Initializes a new instance with the specified base URL for action endpoints.
    /// </summary>
    /// <param name="baseUrl">The base URL of the server (e.g. "https://localhost:5001").</param>
    public ServerActionClientProxyGenerator(string baseUrl = "")
    {
        _baseUrl = baseUrl?.TrimEnd('/') ?? string.Empty;
    }

    /// <summary>
    /// Generates a C# client proxy class for all registered actions.
    /// </summary>
    /// <param name="registry">The action registry containing discovered actions.</param>
    /// <param name="className">The generated class name.</param>
    /// <param name="namespaceName">The namespace for the generated class.</param>
    /// <returns>C# source code for the client proxy class.</returns>
    public string GenerateClientProxy(
        ServerActionRegistry registry,
        string className = "ServerActionsClient",
        string namespaceName = "NextNet.Generated")
    {
        if (registry == null)
            throw new ArgumentNullException(nameof(registry));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS1591, CS8601, CS8602, CS8604");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using NextNet.ServerActions.Results;");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(namespaceName);
        sb.AppendLine("{");
        sb.Append("    /// <summary>").AppendLine();
        sb.Append("    /// Generated client proxy for server actions.").AppendLine();
        sb.Append("    /// </summary>").AppendLine();
        sb.Append("    public static partial class ").Append(className).AppendLine();
        sb.AppendLine("    {");

        foreach (var action in registry.GetAllActions())
        {
            EmitMethod(sb, action);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void EmitMethod(StringBuilder sb, ServerActionDescriptor action)
    {
        var methodName = GetSafeMethodName(action);
        var hasReturnType = action.MethodInfo.ReturnType != typeof(void) &&
                           action.MethodInfo.ReturnType != typeof(Task);

        var returnType = hasReturnType
            ? GetResultTypeName(action.MethodInfo.ReturnType)
            : "ActionResult";

        var deserializableParams = action.Parameters
            .Where(p => !p.IsService && !p.IsCancellationToken)
            .ToList();

        // Build parameter list
        var paramList = new List<string>();
        foreach (var p in deserializableParams)
        {
            paramList.Add($"{GetTypeName(p.ParameterType)} {p.Name}");
        }

        var hasCancellationToken = action.Parameters.Any(p => p.IsCancellationToken);
        if (hasCancellationToken)
        {
            paramList.Add("CancellationToken cancellationToken = default");
        }
        else
        {
            paramList.Add("CancellationToken cancellationToken = default");
        }

        var paramSignature = string.Join(", ", paramList);

        sb.AppendLine();
        sb.Append("        /// <summary>").AppendLine();
        sb.Append("        /// Invokes the ").Append(action.ActionName).AppendLine(" action.");
        sb.Append("        /// </summary>").AppendLine();
        sb.Append("        public static async Task<").Append(returnType).Append("> ")
          .Append(methodName).Append("(").Append(paramSignature).AppendLine(")");
        sb.AppendLine("        {");

        var endpointUrl = string.IsNullOrEmpty(_baseUrl)
            ? action.Route
            : $"{_baseUrl}{action.Route}";

        if (deserializableParams.Count == 0)
        {
            sb.Append("            var response = await HttpClient.PostAsJsonAsync<object>(")
              .Append("\"").Append(endpointUrl).Append("\", null, cancellationToken)")
              .AppendLine(";");
        }
        else if (deserializableParams.Count == 1)
        {
            var p = deserializableParams[0];
            sb.Append("            var response = await HttpClient.PostAsJsonAsync(")
              .Append("\"").Append(endpointUrl).Append("\", ")
              .Append(p.Name).Append(", cancellationToken)")
              .AppendLine(";");
        }
        else
        {
            // Create anonymous object for multiple params
            sb.Append("            var payload = new { ");
            for (var i = 0; i < deserializableParams.Count; i++)
            {
                var p = deserializableParams[i];
                sb.Append(p.Name).Append(" = ").Append(p.Name);
                if (i < deserializableParams.Count - 1)
                    sb.Append(", ");
            }
            sb.AppendLine(" };");
            sb.Append("            var response = await HttpClient.PostAsJsonAsync(")
              .Append("\"").Append(endpointUrl).Append("\", payload, cancellationToken)")
              .AppendLine(";");
        }

        if (hasReturnType)
        {
            sb.Append("            return (await response.Content.ReadFromJsonAsync<")
              .Append(returnType).Append(">(options: default, cancellationToken))!")
              .AppendLine(";");
        }
        else
        {
            sb.Append("            return (await response.Content.ReadFromJsonAsync<ActionResult>(")
              .Append("options: default, cancellationToken))!")
              .AppendLine(";");
        }

        sb.AppendLine("        }");
    }

    private static string GetSafeMethodName(ServerActionDescriptor action)
    {
        var name = action.ActionName;
        // Ensure it's a valid C# identifier
        if (name.Length > 0 && char.IsLetter(name[0]) || name[0] == '_')
            return name;
        return "_" + name;
    }

    private static string GetTypeName(Type type)
    {
        if (type == typeof(string)) return "string";
        if (type == typeof(int)) return "int";
        if (type == typeof(long)) return "long";
        if (type == typeof(double)) return "double";
        if (type == typeof(decimal)) return "decimal";
        if (type == typeof(bool)) return "bool";
        if (type == typeof(char)) return "char";
        if (type == typeof(Guid)) return "Guid";
        if (type == typeof(DateTime)) return "DateTime";
        if (type == typeof(DateTimeOffset)) return "DateTimeOffset";
        if (type == typeof(byte)) return "byte";
        if (type == typeof(short)) return "short";
        if (type == typeof(float)) return "float";
        if (type == typeof(uint)) return "uint";
        if (type == typeof(ulong)) return "ulong";
        if (type == typeof(ushort)) return "ushort";

        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
        {
            return GetTypeName(type.GetGenericArguments()[0]) + "?";
        }

        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Task<>))
        {
            return GetTypeName(type.GetGenericArguments()[0]);
        }

        return type.FullName ?? type.Name;
    }

    private static string GetResultTypeName(Type returnType)
    {
        // Unwrap Task<T>
        var actualType = returnType;
        if (returnType.IsGenericType && returnType.GetGenericTypeDefinition() == typeof(Task<>))
        {
            actualType = returnType.GetGenericArguments()[0];
        }

        if (actualType.IsGenericType && actualType.GetGenericTypeDefinition() == typeof(ActionResult<>))
        {
            var dataType = actualType.GetGenericArguments()[0];
            return $"ActionResult<{GetTypeName(dataType)}>";
        }

        if (actualType == typeof(ActionResult) || actualType == typeof(Results.ActionResult))
        {
            return "ActionResult";
        }

        return $"ActionResult<{GetTypeName(actualType)}>";
    }
}
