namespace NextNet.Data.Dapper.Internal;

/// <summary>
/// Embedded string templates for scaffold code generation.
/// Templates use {{PLACEHOLDER}} syntax for substitution.
/// </summary>
/// <remarks>
/// <para>
/// These templates are used by <see cref="DapperScaffoldProvider"/> when generating
/// model classes, repository classes, and CRUD server actions.
/// </para>
/// <para>
/// All generated SQL uses Dapper's parameterized syntax (<c>@paramName</c>).
/// No string concatenation of user inputs is present in these templates.
/// </para>
/// </remarks>
internal static class ScaffoldTemplates
{
    /// <summary>
    /// Template for POCO model classes.
    /// </summary>
    internal const string ModelTemplate = @"// <auto-generated />
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace {{ModelNamespace}};

/// <summary>
/// Represents a {{EntityName}} entity.
/// </summary>
{{TableAttribute}}
public class {{EntityName}}
{
{{KeyDeclaration}}
{{Properties}}
}
";

    /// <summary>
    /// Template for Dapper repository classes with parameterized SQL.
    /// </summary>
    internal const string RepositoryTemplate = @"// <auto-generated />
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Data.SqlClient;
using NextNet.Data.Dapper;

namespace {{RepositoryNamespace}};

/// <summary>
/// Dapper repository for <see cref=""{{ModelNamespace}}.{{EntityName}}""/>.
/// </summary>
public class {{EntityName}}Repository : DapperRepository<{{ModelNamespace}}.{{EntityName}}>
{
    /// <summary>
    /// Initializes a new instance of <see cref=""{{EntityName}}Repository""/>.
    /// </summary>
    /// <param name=""connectionManager"">The connection manager.</param>
    /// <param name=""logger"">Optional logger.</param>
    public {{EntityName}}Repository(
        DapperConnectionManager connectionManager,
        ILogger<{{EntityName}}Repository>? logger = null)
        : base(connectionManager, connectionName: ""{{ConnectionName}}"", logger: logger)
    {
    }
}
";

    /// <summary>
    /// Template for Create server action.
    /// </summary>
    internal const string CreateActionTemplate = @"// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using {{ModelNamespace}};
using {{RepositoryNamespace}};
using NextNet.ServerActions;

namespace {{ActionsNamespace}};

/// <summary>
/// Creates a new {{EntityName}}.
/// </summary>
public sealed class Create{{EntityName}}Action : IServerAction
{
    private readonly {{EntityName}}Repository _repository;

    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    public Create{{EntityName}}Action({{EntityName}}Repository repository)
    {
        _repository = repository;
    }

    /// <summary>
    /// Executes the create action.
    /// </summary>
    public async Task ExecuteAsync({{EntityName}} entity, CancellationToken cancellationToken = default)
    {
        await _repository.InsertAsync(entity, cancellationToken);
    }
}
";

    /// <summary>
    /// Template for List server action.
    /// </summary>
    internal const string ListActionTemplate = @"// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using {{ModelNamespace}};
using {{RepositoryNamespace}};
using NextNet.Data.Abstractions.Models;
using NextNet.ServerActions;

namespace {{ActionsNamespace}};

/// <summary>
/// Lists {{EntityName}} entities with pagination.
/// </summary>
public sealed class List{{EntityName}}Action : IServerAction
{
    private readonly {{EntityName}}Repository _repository;

    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    public List{{EntityName}}Action({{EntityName}}Repository repository)
    {
        _repository = repository;
    }

    /// <summary>
    /// Executes the list action.
    /// </summary>
    public async Task<PagedResult<{{EntityName}}>> ExecuteAsync(
        RepositoryQueryOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        return await _repository.GetAllAsync(options, cancellationToken);
    }
}
";

    /// <summary>
    /// Template for Detail/Get server action.
    /// </summary>
    internal const string DetailActionTemplate = @"// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using {{ModelNamespace}};
using {{RepositoryNamespace}};
using NextNet.ServerActions;

namespace {{ActionsNamespace}};

/// <summary>
/// Gets a single {{EntityName}} by ID.
/// </summary>
public sealed class Get{{EntityName}}Action : IServerAction
{
    private readonly {{EntityName}}Repository _repository;

    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    public Get{{EntityName}}Action({{EntityName}}Repository repository)
    {
        _repository = repository;
    }

    /// <summary>
    /// Executes the get action.
    /// </summary>
    public async Task<{{EntityName}}?> ExecuteAsync(object id, CancellationToken cancellationToken = default)
    {
        return await _repository.FindAsync(id, cancellationToken);
    }
}
";

    /// <summary>
    /// Template for Update server action.
    /// </summary>
    internal const string UpdateActionTemplate = @"// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using {{ModelNamespace}};
using {{RepositoryNamespace}};
using NextNet.ServerActions;

namespace {{ActionsNamespace}};

/// <summary>
/// Updates an existing {{EntityName}}.
/// </summary>
public sealed class Update{{EntityName}}Action : IServerAction
{
    private readonly {{EntityName}}Repository _repository;

    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    public Update{{EntityName}}Action({{EntityName}}Repository repository)
    {
        _repository = repository;
    }

    /// <summary>
    /// Executes the update action.
    /// </summary>
    public async Task ExecuteAsync({{EntityName}} entity, CancellationToken cancellationToken = default)
    {
        await _repository.UpdateAsync(entity, cancellationToken);
    }
}
";

    /// <summary>
    /// Template for Delete server action.
    /// </summary>
    internal const string DeleteActionTemplate = @"// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using {{ModelNamespace}};
using {{RepositoryNamespace}};
using NextNet.ServerActions;

namespace {{ActionsNamespace}};

/// <summary>
/// Deletes a {{EntityName}} by ID.
/// </summary>
public sealed class Delete{{EntityName}}Action : IServerAction
{
    private readonly {{EntityName}}Repository _repository;

    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    public Delete{{EntityName}}Action({{EntityName}}Repository repository)
    {
        _repository = repository;
    }

    /// <summary>
    /// Executes the delete action.
    /// </summary>
    public async Task ExecuteAsync(object id, CancellationToken cancellationToken = default)
    {
        await _repository.DeleteAsync(id, cancellationToken);
    }
}
";
}
