namespace NextNet.Data.Dapper.Internal;

/// <summary>
/// Builds parameterized SQL statements for CRUD operations using Dapper's parameter syntax.
/// </summary>
/// <remarks>
/// <para>
/// All generated SQL uses <c>@paramName</c> parameterized syntax to prevent SQL injection.
/// No string concatenation of user input is performed in this class.
/// </para>
/// <para>
/// SQL dialect differences (pagination style, identity retrieval) are controlled by
/// <see cref="DapperRepositoryOptions.PaginationStyle"/> and <see cref="DapperRepositoryOptions.KeyIsAutoGenerated"/>.
/// </para>
/// </remarks>
internal static class SqlBuilder
{
    /// <summary>
    /// Builds a parameterized SELECT query by primary key.
    /// Default: <c>SELECT * FROM {Table} WHERE {Key} = @Id</c>
    /// </summary>
    internal static string BuildFind(EntityMetadata metadata)
    {
        return $"SELECT * FROM {metadata.QualifiedTableName} WHERE {QuoteName(metadata.KeyColumn)} = @Id";
    }

    /// <summary>
    /// Builds a parameterized COUNT query.
    /// Default: <c>SELECT COUNT(*) FROM {Table}</c>
    /// </summary>
    internal static string BuildCount(EntityMetadata metadata, string? filter = null)
    {
        var sql = $"SELECT COUNT(*) FROM {metadata.QualifiedTableName}";
        if (!string.IsNullOrWhiteSpace(filter))
        {
            sql += $" WHERE {filter}";
        }
        return sql;
    }

    /// <summary>
    /// Builds a parameterized SELECT query with pagination and optional sorting.
    /// Uses either OFFSET/FETCH or LIMIT/OFFSET syntax based on <see cref="PaginationStyle"/>.
    /// </summary>
    internal static string BuildGetAll(
        EntityMetadata metadata,
        PaginationStyle paginationStyle,
        string? sortBy = null,
        bool sortDescending = false,
        string? filter = null)
    {
        var sql = $"SELECT * FROM {metadata.QualifiedTableName}";

        if (!string.IsNullOrWhiteSpace(filter))
        {
            sql += $" WHERE {filter}";
        }

        // Apply sorting (column name already whitelist-validated by caller)
        var sortColumn = !string.IsNullOrWhiteSpace(sortBy) ? QuoteName(sortBy) : QuoteName(metadata.KeyColumn);
        sql += $" ORDER BY {sortColumn} {(sortDescending ? "DESC" : "ASC")}";

        sql += paginationStyle switch
        {
            PaginationStyle.LimitOffset => " OFFSET @Offset ROWS LIMIT @Limit ROWS",
            _ => " OFFSET @Offset ROWS FETCH NEXT @Limit ROWS ONLY"
        };

        return sql;
    }

    /// <summary>
    /// Builds a parameterized INSERT query.
    /// Includes <c>SELECT CAST(SCOPE_IDENTITY() AS INT)</c> when key is auto-generated.
    /// </summary>
    internal static string BuildInsert(EntityMetadata metadata, bool keyIsAutoGenerated)
    {
        var columns = string.Join(", ", metadata.InsertColumns.Select(QuoteName));
        var values = string.Join(", ", metadata.InsertColumns.Select(c => $"@{c}"));

        var sql = $"INSERT INTO {metadata.QualifiedTableName} ({columns}) VALUES ({values})";

        if (keyIsAutoGenerated)
        {
            sql += "; SELECT CAST(SCOPE_IDENTITY() AS INT)";
        }

        return sql;
    }

    /// <summary>
    /// Builds a parameterized UPDATE query.
    /// Default: <c>UPDATE {Table} SET {SetClause} WHERE {Key} = @Id</c>
    /// </summary>
    internal static string BuildUpdate(EntityMetadata metadata)
    {
        var setClause = string.Join(", ", metadata.UpdateColumns.Select(c => $"{QuoteName(c)} = @{c}"));
        return $"UPDATE {metadata.QualifiedTableName} SET {setClause} WHERE {QuoteName(metadata.KeyColumn)} = @{metadata.KeyColumn}";
    }

    /// <summary>
    /// Builds a parameterized DELETE query.
    /// Default: <c>DELETE FROM {Table} WHERE {Key} = @Id</c>
    /// </summary>
    internal static string BuildDelete(EntityMetadata metadata)
    {
        return $"DELETE FROM {metadata.QualifiedTableName} WHERE {QuoteName(metadata.KeyColumn)} = @Id";
    }

    /// <summary>
    /// Quotes a column or table name. Currently wraps in square brackets (SQL Server).
    /// </summary>
    internal static string QuoteName(string name)
    {
        if (name.Contains(' ') || name.Contains('-') || name.Contains('.') ||
            name.StartsWith('[') || name.Contains(']'))
        {
            return name; // Already quoted or complex
        }
        return $"[{name}]";
    }
}
