using System.Collections.Generic;
using System.Text;
using NextNet.SourceGenerators.ServerActions;

namespace NextNet.SourceGenerators.ServerActions.ServerActionEmitters
{
    /// <summary>
    /// Generates Minimal API endpoint registration code (MapPost) for server actions.
    /// </summary>
    internal static class ServerActionEndpointEmitter
    {
        /// <summary>
        /// Emits source code for a static class that registers all server action endpoints.
        /// </summary>
        /// <param name="actions">The list of discovered server actions.</param>
        /// <param name="ns">The namespace for the generated class.</param>
        /// <returns>C# source code.</returns>
        public static string Emit(List<ServerActionMethodModel> actions, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Builder;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.AspNetCore.Routing;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using NextNet.ServerActions;");
            sb.AppendLine("using NextNet.ServerActions.ServerActions;");
            sb.AppendLine("using NextNet.ServerActions.Results;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Generated endpoint registration for all server actions.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).AppendLine("public static class ServerActionEndpointRegistry");
            sb.Append(indent).AppendLine("{");

            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Registers all server action endpoints via MapPost.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public static void MapServerActions(")
              .Append("this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,")
              .AppendLine();
            sb.Append(indent).Append("        global::NextNet.ServerActions.ServerActions.ServerActionExecutor executor)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");

            foreach (var action in actions)
            {
                EmitEndpoint(sb, action, indent + "        ");
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();

            // Also emit direct registration extension on WebApplication
            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Extension methods for registering server action endpoints.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).AppendLine("public static class ServerActionWebApplicationExtensions");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Maps all server action endpoints.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public static global::Microsoft.AspNetCore.Routing.")
              .Append("IEndpointRouteBuilder MapServerActions(")
              .AppendLine();
            sb.Append(indent).Append("        this global::Microsoft.AspNetCore.Routing.")
              .Append("IEndpointRouteBuilder app)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");

            // Generate direct inline handlers
            sb.Append(indent).AppendLine("        var executor = app.ServiceProvider")
              .Append(".GetRequiredService<ServerActionExecutor>();")
              .AppendLine();

            foreach (var action in actions)
            {
                sb.Append(indent).Append("        app.MapPost(\"").Append(action.Route)
                  .Append("\", async (HttpContext context) =>").AppendLine();
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).Append("            await executor.ExecuteAsync(context, \"")
                  .Append(action.ActionName).Append("\", context.RequestAborted);")
                  .AppendLine();
                sb.Append(indent).AppendLine("        });");
                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("        return app;");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitEndpoint(StringBuilder sb, ServerActionMethodModel action, string indent)
        {
            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).Append("/// ").Append(action.ActionName)
              .Append(" — ").AppendLine(action.Route);
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("app.MapPost(\"").Append(action.Route)
              .Append("\", async (HttpContext context) =>").AppendLine();
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    await executor.ExecuteAsync(context, \"")
              .Append(action.ActionName).Append("\", context.RequestAborted);")
              .AppendLine();
            sb.Append(indent).AppendLine("});");
            sb.AppendLine();
        }
    }
}
