using System.Collections.Generic;
using System.Linq;
using System.Text;
using NextNet.SourceGenerators.ServerActions;

namespace NextNet.SourceGenerators.ServerActions.ServerActionEmitters;
    /// <summary>
    /// Generates C# client proxy source code for server actions.
    /// The generated class uses HttpClient to call server action endpoints.
    /// </summary>
    internal static class ServerActionClientProxyEmitter
    {
        /// <summary>
        /// Emits a client proxy class for the given server actions.
        /// </summary>
        /// <param name="actions">The discovered server actions.</param>
        /// <param name="ns">Target namespace.</param>
        /// <param name="className">Generated class name.</param>
        /// <returns>C# source code for the client proxy.</returns>
        public static string Emit(
            List<ServerActionMethodModel> actions,
            string ns,
            string className = "ServerActionsClient")
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS1591, CS8601, CS8602, CS8604");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Net.Http;");
            sb.AppendLine("using System.Net.Http.Json;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using NextNet.ServerActions.Results;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Generated client proxy for server actions.");
            sb.Append(indent).AppendLine("/// Set <c>BaseUrl</c> to the server's base URL before calling action methods.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("public static partial class ").Append(className).AppendLine();
            sb.Append(indent).AppendLine("{");

            // HttpClient property
            sb.Append(indent).AppendLine("    private static readonly HttpClient _httpClient = new();");
            sb.AppendLine();

            foreach (var action in actions)
            {
                EmitMethod(sb, action, indent);
            }

            sb.Append(indent).AppendLine("}");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitMethod(StringBuilder sb, ServerActionMethodModel action, string indent)
        {
            // Determine return type
            var hasReturnType = !action.ReturnsVoid;
            var returnType = "ActionResult";
            var innerType = "";

            if (!action.ReturnsVoid && action.ReturnsTask && !string.IsNullOrEmpty(action.TaskResultTypeName))
            {
                var taskResultType = action.TaskResultTypeName;
                if (taskResultType.StartsWith("global::NextNet.ServerActions.Results.ActionResult<"))
                {
                    // Extract the generic type argument
                    var start = taskResultType.IndexOf('<') + 1;
                    var end = taskResultType.LastIndexOf('>');
                    if (start > 0 && end > start)
                    {
                        innerType = taskResultType.Substring(start, end - start);
                        returnType = "ActionResult<" + innerType + ">";
                    }
                    else
                    {
                        returnType = "ActionResult";
                    }
                }
                else
                {
                    // Return type is not ActionResult — wrap it
                    returnType = "ActionResult";
                }
            }
            else if (!action.ReturnsVoid && action.ReturnsTask)
            {
                returnType = "ActionResult";
            }

            // Parameters
            var deserializableParams = action.Parameters
                .Where(p => !p.IsService && !p.IsCancellationToken)
                .ToList();

            var paramList = new List<string>();
            foreach (var p in deserializableParams)
            {
                paramList.Add($"{p.TypeName} {p.Name}");
            }
            paramList.Add("CancellationToken cancellationToken = default");

            var paramSignature = string.Join(", ", paramList);

            sb.AppendLine();
            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).Append("    /// Invokes the ").Append(action.ActionName).AppendLine(" action.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public static async Task<").Append(returnType).Append("> ")
              .Append(action.MethodName).Append("(").Append(paramSignature).AppendLine(")");
            sb.Append(indent).AppendLine("    {");

            if (deserializableParams.Count == 0)
            {
                sb.Append(indent).Append("        var response = await _httpClient.PostAsJsonAsync<object>(")
                  .Append("\"").Append(action.Route).Append("\", null, cancellationToken)")
                  .AppendLine(";");
            }
            else if (deserializableParams.Count == 1)
            {
                var p = deserializableParams[0];
                sb.Append(indent).Append("        var response = await _httpClient.PostAsJsonAsync(")
                  .Append("\"").Append(action.Route).Append("\", ")
                  .Append(p.Name).Append(", cancellationToken)")
                  .AppendLine(";");
            }
            else
            {
                sb.Append(indent).Append("        var payload = new { ");
                for (var i = 0; i < deserializableParams.Count; i++)
                {
                    var p = deserializableParams[i];
                    sb.Append(p.Name).Append(" = ").Append(p.Name);
                    if (i < deserializableParams.Count - 1)
                        sb.Append(", ");
                }
                sb.AppendLine(" };");
                sb.Append(indent).Append("        var response = await _httpClient.PostAsJsonAsync(")
                  .Append("\"").Append(action.Route).Append("\", payload, cancellationToken)")
                  .AppendLine(";");
            }

            if (!action.ReturnsVoid)
            {
                sb.Append(indent).Append("        return (await response.Content.ReadFromJsonAsync<")
                  .Append(returnType).AppendLine(">(options: default, cancellationToken))!;");
            }
            else
            {
                sb.Append(indent).Append("        return (await response.Content.ReadFromJsonAsync<ActionResult>(")
                  .AppendLine("options: default, cancellationToken))!;");
            }

            sb.Append(indent).AppendLine("    }");
        }
    }
