using System.Collections.Generic;
using System.Text;
using NextNet.SourceGenerators.ServerActions;

namespace NextNet.SourceGenerators.ServerActions.ServerActionEmitters
{
    /// <summary>
    /// Generates DI registration code for server action classes.
    /// </summary>
    internal static class ServerActionRegistrationEmitter
    {
        /// <summary>
        /// Emits a static class that registers all server action types in the DI container.
        /// </summary>
        /// <param name="actions">The discovered server actions.</param>
        /// <param name="ns">Target namespace.</param>
        /// <returns>C# source code.</returns>
        public static string Emit(List<ServerActionMethodModel> actions, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Generated DI registration for server action types.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).AppendLine("public static class ServerActionServiceRegistration");
            sb.Append(indent).AppendLine("{");

            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Registers all server action classes in the DI container.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).Append("    public static void RegisterServerActions(")
              .Append("this IServiceCollection services)")
              .AppendLine();
            sb.Append(indent).AppendLine("    {");

            var registeredTypes = new HashSet<string>();

            foreach (var action in actions)
            {
                if (!action.IsStatic && !string.IsNullOrEmpty(action.DeclaringType))
                {
                    if (registeredTypes.Add(action.DeclaringType))
                    {
                        sb.Append(indent).Append("        services.AddTransient<")
                          .Append(action.DeclaringType).AppendLine(">();");
                    }
                }
            }

            if (registeredTypes.Count == 0)
            {
                sb.Append(indent).AppendLine("        // No instance-based server actions to register.");
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }
    }
}
