using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NextNet.SourceGenerators.ServerActions.ServerActionEmitters;
using NextNet.SourceGenerators.Utils;

namespace NextNet.SourceGenerators.ServerActions;
    /// <summary>
    /// Incremental source generator that discovers methods and classes marked with
    /// <c>[ServerAction]</c> and generates:
    /// - Minimal API endpoint registration (MapPost)
    /// - Client proxy classes
    /// - DI registration
    ///
    /// Pipeline:
    ///   1. <c>RegisterPostInitializationOutput</c> emits the <c>ServerActionAttribute</c>.
    ///   2. <c>ForAttributeWithMetadataName</c> discovers attributed methods.
    ///   3. <c>RegisterSourceOutput</c> emits endpoint + client proxy + registration code.
    /// </summary>
    /// <example>
    /// The generator discovers methods annotated with <c>[ServerAction]</c> and emits
    /// a <c>MapPost</c> endpoint, a client proxy class, and DI registration automatically.
    /// <code>
    /// // Usage in a page handler:
    /// [ServerAction(Name = "createUser", RequireAuth = true)]
    /// public async Task&lt;ActionResult&gt; CreateUser(string name, string email) { ... }
    /// </code>
    /// </example>
    [Generator]
    public sealed class ServerActionGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Fully qualified name of the server action attribute.
        /// </summary>
        internal const string ServerActionAttributeName = "NextNet.ServerActions.ServerActionAttribute";

        /// <summary>
        /// Namespace for generated code.
        /// </summary>
        internal const string GeneratedNamespace = "NextNet.Generated.ServerActions";

        /// <summary>
        /// Embedded marker attribute source emitted during initialization.
        /// This allows the source generator to discover [ServerAction]-annotated methods
        /// even if the attribute is defined in a referenced assembly.
        /// </summary>
        internal const string MarkerAttributeSource = @"// <auto-generated />
#nullable enable
namespace NextNet.ServerActions
{
    /// <summary>
    /// Marks a class or static method as a server action.
    /// Server actions are automatically exposed as HTTP POST endpoints at <c>/_actions/{name}</c>.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class ServerActionAttribute : System.Attribute
    {
        public string? Name { get; set; }
        public string? Route { get; set; }
        public bool RequireAuth { get; set; } = false;
    }
}";

        /// <summary>
        /// Initializes the incremental generator pipeline.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Step 1: Emit the marker attribute (in case the user hasn't referenced the attribute assembly)
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("NextNet.ServerActionAttribute.g.cs",
                    SourceText.From(MarkerAttributeSource, Encoding.UTF8));
            });

            // Step 2: Discover methods with [ServerAction] attribute
            var actionMethods = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ServerActionAttributeName,
                    static (node, _) => node is MethodDeclarationSyntax,
                    static (ctx, _) => ExtractActionMethod(ctx))
                .Where(static m => m != null)
                .Collect();

            // Step 3: Generate output
            context.RegisterSourceOutput(actionMethods, static (spc, actionList) =>
            {
                try
                {
                    if (actionList.IsDefaultOrEmpty)
                    {
                        EmitEmptyStubs(spc);
                        return;
                    }

                    var validActions = actionList
                        .Where(static a => a != null)
                        .Select(static a => a!)
                        .ToList();

                    if (validActions.Count == 0)
                    {
                        EmitEmptyStubs(spc);
                        return;
                    }

                    // Generate endpoint registration
                    var endpointSource = ServerActionEndpointEmitter.Emit(validActions, GeneratedNamespace);
                    spc.AddSource("NextNet.ServerActions.Endpoints.g.cs",
                        SourceText.From(endpointSource, Encoding.UTF8));

                    // Generate client proxy
                    var proxySource = ServerActionClientProxyEmitter.Emit(validActions, GeneratedNamespace);
                    spc.AddSource("NextNet.ServerActions.ClientProxy.g.cs",
                        SourceText.From(proxySource, Encoding.UTF8));

                    // Generate DI registration
                    var registrationSource = ServerActionRegistrationEmitter.Emit(validActions, GeneratedNamespace);
                    spc.AddSource("NextNet.ServerActions.Registration.g.cs",
                        SourceText.From(registrationSource, Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InternalError,
                        Location.None,
                        ex.Message));
                }
            });
        }

        /// <summary>
        /// Extracts action metadata from a method declaration annotated with [ServerAction].
        /// Only captures string/simple data — never holds onto ISymbol or SyntaxNode references.
        /// </summary>
        private static ServerActionMethodModel? ExtractActionMethod(GeneratorAttributeSyntaxContext ctx)
        {
            try
            {
                if (ctx.TargetSymbol is not IMethodSymbol methodSymbol)
                    return null;

                if (ctx.TargetNode is not MethodDeclarationSyntax methodSyntax)
                    return null;

                // Get the attribute
                var attr = methodSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ServerActionAttributeName);

                if (attr == null)
                    return null;

                // Extract attribute properties
                var actionName = methodSymbol.Name;
                var route = (string?)null;
                var requireAuth = false;

                if (attr.NamedArguments.Length > 0)
                {
                    foreach (var kvp in attr.NamedArguments)
                    {
                        switch (kvp.Key)
                        {
                            case "Name":
                                actionName = kvp.Value.Value?.ToString() ?? methodSymbol.Name;
                                break;
                            case "Route":
                                route = kvp.Value.Value?.ToString();
                                break;
                            case "RequireAuth":
                                requireAuth = kvp.Value.Value is true;
                                break;
                        }
                    }
                }

                // Build the route
                if (string.IsNullOrEmpty(route))
                {
                    route = $"/_actions/{actionName}";
                }

                // Determine return type
                var returnType = methodSymbol.ReturnType;
                var returnTypeName = returnType.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat);
                var returnsVoid = returnType.SpecialType == SpecialType.System_Void;
                var returnsTask = returnTypeName.Contains("System.Threading.Tasks.Task");
                var taskResultTypeName = string.Empty;

                if (returnsTask && returnType is INamedTypeSymbol namedReturn)
                {
                    if (namedReturn.TypeArguments.Length == 1)
                    {
                        taskResultTypeName = namedReturn.TypeArguments[0].ToDisplayString(
                            SymbolDisplayFormat.FullyQualifiedFormat);
                    }
                }

                // Extract declaring type info
                var declaringType = methodSymbol.ContainingType;
                var declaringTypeName = declaringType.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat);
                var declaringNamespace = declaringType.ContainingNamespace?.ToDisplayString() ?? string.Empty;

                // Extract parameters
                var parameters = new List<ServerActionParameterModel>();
                foreach (var param in methodSymbol.Parameters)
                {
                    var paramType = param.Type;
                    var paramTypeName = paramType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat);

                    var isService = IsServiceType(paramType);
                    var isCancellationToken = paramType.SpecialType == SpecialType.None &&
                                             paramTypeName.Contains("System.Threading.CancellationToken");

                    parameters.Add(new ServerActionParameterModel
                    {
                        Name = param.Name,
                        TypeName = paramTypeName,
                        IsService = isService,
                        IsCancellationToken = isCancellationToken
                    });
                }

                return new ServerActionMethodModel
                {
                    ActionName = actionName,
                    Route = route ?? "",
                    DeclaringType = declaringTypeName,
                    MethodName = methodSymbol.Name,
                    IsStatic = methodSymbol.IsStatic,
                    AllowAnonymous = !requireAuth,
                    ReturnTypeName = returnTypeName,
                    ReturnsVoid = returnsVoid,
                    ReturnsTask = returnsTask,
                    TaskResultTypeName = taskResultTypeName,
                    Parameters = parameters,
                    DeclaringNamespace = declaringNamespace
                };
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Determines if a parameter type should be resolved from DI rather than deserialized.
        /// </summary>
        private static bool IsServiceType(ITypeSymbol type)
        {
            if (type == null)
                return false;

            var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (typeName.Contains("System.Threading.CancellationToken"))
                return true;
            if (typeName.Contains("Microsoft.AspNetCore.Http.HttpContext"))
                return true;
            if (typeName.Contains("System.IServiceProvider"))
                return true;

            // Interfaces and abstract classes are typically services
            if (type.TypeKind == TypeKind.Interface)
                return true;
            if (type.IsAbstract)
                return true;

            // Types ending with common DI suffixes
            var name = type.Name;
            if (name.EndsWith("Service") ||
                name.EndsWith("Repository") ||
                name.EndsWith("Provider") ||
                name.EndsWith("Factory") ||
                name.EndsWith("Manager"))
                return true;

            return false;
        }

        /// <summary>
        /// Emits empty stub types so that the generated namespace is always available.
        /// </summary>
        private static void EmitEmptyStubs(SourceProductionContext spc)
        {
            spc.AddSource("NextNet.ServerActions.Endpoints.g.cs",
                SourceText.From(@"// <auto-generated />
#pragma warning disable CS1591
#nullable enable
namespace NextNet.Generated.ServerActions
{
    /// <summary>
    /// No server actions were discovered. This is a placeholder stub.
    /// </summary>
    public static class ServerActionEndpointRegistry
    {
        public static void MapServerActions(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) { }
    }

    public static class ServerActionWebApplicationExtensions
    {
        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapServerActions(
            this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app;
    }
}
", Encoding.UTF8));

            spc.AddSource("NextNet.ServerActions.ClientProxy.g.cs",
                SourceText.From(@"// <auto-generated />
#pragma warning disable CS1591
#nullable enable
namespace NextNet.Generated.ServerActions
{
    /// <summary>
    /// No server actions were discovered. This is a placeholder stub.
    /// </summary>
    public static class ServerActionsClient { }
}
", Encoding.UTF8));

            spc.AddSource("NextNet.ServerActions.Registration.g.cs",
                SourceText.From(@"// <auto-generated />
#pragma warning disable CS1591
#nullable enable
namespace NextNet.Generated.ServerActions
{
    /// <summary>
    /// No server actions were discovered. This is a placeholder stub.
    /// </summary>
    public static class ServerActionServiceRegistration
    {
        public static void RegisterServerActions(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) { }
    }
}
", Encoding.UTF8));
        }
    }
