namespace NextNet.Data.Dapper.Templates;

/// <summary>
/// Embedded string templates for Dapper scaffold code generation.
/// Templates use {{PLACEHOLDER}} syntax for substitution and are consumed
/// by <see cref="Scaffolding.DapperScaffoldProvider"/>.
/// </summary>
/// <remarks>
/// <para>
/// These templates produce plain entity classes, Dapper repository classes,
/// and combined CRUD API route files. All generated SQL uses Dapper's
/// parameterized syntax (<c>@paramName</c>).
/// </para>
/// <para>
/// Unlike <see cref="Internal.ScaffoldTemplates"/> which uses separate files
/// per action, <see cref="CRUD_ROUTE_TEMPLATE"/> combines all CRUD operations
/// into a single API route file.
/// </para>
/// </remarks>
internal static class DapperTemplates
{
    /// <summary>
    /// Template for a basic entity/POCO class with optional table mapping.
    /// </summary>
    /// <remarks>
    /// Supported placeholders:
    /// <list type="bullet">
    ///   <item><c>{{ModelNamespace}}</c> — The target namespace.</item>
    ///   <item><c>{{EntityName}}</c> — The entity class name.</item>
    ///   <item><c>{{TableAttribute}}</c> — The <c>[Table]</c> attribute or empty string.</item>
    ///   <item><c>{{Summary}}</c> — An XML doc summary for the class.</item>
    ///   <item><c>{{KeyDeclaration}}</c> — The primary key property declaration.</item>
    ///   <item><c>{{Properties}}</c> — All other property declarations.</item>
    /// </list>
    /// </remarks>
    internal const string MODEL_TEMPLATE = @"// <auto-generated />
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace {{ModelNamespace}};

/// <summary>
/// {{Summary}}
/// </summary>
{{TableAttribute}}
public class {{EntityName}}
{
{{KeyDeclaration}}
{{Properties}}
}
";

    /// <summary>
    /// Template for a Dapper repository class that extends <see cref="DapperRepository{T}"/>.
    /// </summary>
    /// <remarks>
    /// Supported placeholders:
    /// <list type="bullet">
    ///   <item><c>{{ModelNamespace}}</c> — Namespace of the entity model.</item>
    ///   <item><c>{{RepositoryNamespace}}</c> — Namespace for the repository.</item>
    ///   <item><c>{{EntityName}}</c> — The entity class name.</item>
    ///   <item><c>{{ConnectionName}}</c> — The connection name to use.</item>
    /// </list>
    /// </remarks>
    internal const string REPOSITORY_TEMPLATE = @"// <auto-generated />
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Data.SqlClient;
using NextNet.Data.Dapper;
using {{ModelNamespace}};

namespace {{RepositoryNamespace}};

/// <summary>
/// Dapper repository for <see cref=""{{EntityName}}""/> CRUD operations.
/// </summary>
public class {{EntityName}}Repository : DapperRepository<{{EntityName}}>
{
    /// <summary>
    /// Initializes a new instance of <see cref=""{{EntityName}}Repository""/>.
    /// </summary>
    /// <param name=""connectionManager"">The connection manager for database access.</param>
    /// <param name=""logger"">Optional logger for query diagnostics.</param>
    public {{EntityName}}Repository(
        DapperConnectionManager connectionManager,
        ILogger<{{EntityName}}Repository>? logger = null)
        : base(connectionManager, connectionName: ""{{ConnectionName}}"", logger: logger)
    {
    }
}
";

    /// <summary>
    /// Template for a combined CRUD API route file that maps all operations
    /// (Create, Read, Update, Delete) to HTTP endpoints.
    /// </summary>
    /// <remarks>
    /// Supported placeholders:
    /// <list type="bullet">
    ///   <item><c>{{ModelNamespace}}</c> — Namespace of the entity model.</item>
    ///   <item><c>{{RepositoryNamespace}}</c> — Namespace of the repository.</item>
    ///   <item><c>{{ActionsNamespace}}</c> — Namespace for the route class.</item>
    ///   <item><c>{{EntityName}}</c> — The entity class name.</item>
    ///   <item><c>{{EntityNameLower}}</c> — Lowercased entity name for route paths.</item>
    /// </list>
    /// </remarks>
    internal const string CRUD_ROUTE_TEMPLATE = @"// <auto-generated />
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using {{ModelNamespace}};
using {{RepositoryNamespace}};

namespace {{ActionsNamespace}};

/// <summary>
/// CRUD API route for <see cref=""{{EntityName}}""/> entities.
/// </summary>
[ApiController]
[Route(""api/{{EntityNameLower}}"")]
public sealed class {{EntityName}}Controller : ControllerBase
{
    private readonly {{EntityName}}Repository _repository;
    private readonly ILogger<{{EntityName}}Controller> _logger;

    /// <summary>
    /// Initializes a new instance of <see cref=""{{EntityName}}Controller""/>.
    /// </summary>
    /// <param name=""repository"">The entity repository.</param>
    /// <param name=""logger"">The logger instance.</param>
    public {{EntityName}}Controller(
        {{EntityName}}Repository repository,
        ILogger<{{EntityName}}Controller> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Lists all entities with optional pagination.
    /// </summary>
    /// <param name=""page"">The page number (1-based).</param>
    /// <param name=""pageSize"">The number of items per page.</param>
    /// <param name=""cancellationToken"">A token to cancel the operation.</param>
    /// <returns>A paged result of entities.</returns>
    [HttpGet]
    public async Task<ActionResult<PagedResult<{{EntityName}}>>> GetAll(
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20,
        CancellationToken cancellationToken = default)
    {
        var options = new RepositoryQueryOptions(page: page, pageSize: pageSize);
        var result = await _repository.GetAllAsync(options, cancellationToken);
        return Ok(result);
    }

    /// <summary>
    /// Gets a single entity by ID.
    /// </summary>
    /// <param name=""id"">The entity ID.</param>
    /// <param name=""cancellationToken"">A token to cancel the operation.</param>
    /// <returns>The entity if found; otherwise 404.</returns>
    [HttpGet(""{id}"")]
    public async Task<ActionResult<{{EntityName}}>> GetById(
        object id,
        CancellationToken cancellationToken = default)
    {
        var entity = await _repository.FindAsync(id, cancellationToken);
        if (entity is null)
            return NotFound();
        return Ok(entity);
    }

    /// <summary>
    /// Creates a new entity.
    /// </summary>
    /// <param name=""entity"">The entity to create.</param>
    /// <param name=""cancellationToken"">A token to cancel the operation.</param>
    /// <returns>The created entity with its generated ID.</returns>
    [HttpPost]
    public async Task<ActionResult<{{EntityName}}>> Create(
        [FromBody] {{EntityName}} entity,
        CancellationToken cancellationToken = default)
    {
        await _repository.InsertAsync(entity, cancellationToken);
        return CreatedAtAction(nameof(GetById), new { id = GetEntityId(entity) }, entity);
    }

    /// <summary>
    /// Updates an existing entity.
    /// </summary>
    /// <param name=""id"">The entity ID.</param>
    /// <param name=""entity"">The updated entity data.</param>
    /// <param name=""cancellationToken"">A token to cancel the operation.</param>
    /// <returns>204 No Content on success.</returns>
    [HttpPut(""{id}"")]
    public async Task<IActionResult> Update(
        object id,
        [FromBody] {{EntityName}} entity,
        CancellationToken cancellationToken = default)
    {
        // Ensure the ID in the URL matches the entity
        SetEntityId(entity, id);
        await _repository.UpdateAsync(entity, cancellationToken);
        return NoContent();
    }

    /// <summary>
    /// Deletes an entity by ID.
    /// </summary>
    /// <param name=""id"">The entity ID to delete.</param>
    /// <param name=""cancellationToken"">A token to cancel the operation.</param>
    /// <returns>204 No Content on success.</returns>
    [HttpDelete(""{id}"")]
    public async Task<IActionResult> Delete(
        object id,
        CancellationToken cancellationToken = default)
    {
        await _repository.DeleteAsync(id, cancellationToken);
        return NoContent();
    }

    private static object GetEntityId({{EntityName}} entity)
    {
        // Reflection-based ID extraction for the CreatedAtAction response
        var prop = typeof({{EntityName}}).GetProperty(""Id"") ?? typeof({{EntityName}}).GetProperty(""{{EntityName}}Id"");
        return prop?.GetValue(entity) ?? throw new InvalidOperationException(""Entity must have an 'Id' or '{{EntityName}}Id' property."");
    }

    private static void SetEntityId({{EntityName}} entity, object id)
    {
        var prop = typeof({{EntityName}}).GetProperty(""Id"") ?? typeof({{EntityName}}).GetProperty(""{{EntityName}}Id"");
        if (prop is not null && prop.CanWrite)
        {
            prop.SetValue(entity, Convert.ChangeType(id, prop.PropertyType));
        }
    }
}
";
}
